/-
# Toward discharging `jvn`: the von Neumann / Jankov measurable-selection theorem

The planar-Kakeya headline `davies_kakeya_2d` is already complete and axiom-clean via the elementary
open-cover route. This file develops the *independent* second route's missing ingredient: the abstract
measurable selection theorem packaged in `Selection.kakeya_aeMeasurable_selection_of_jvn` as the
hypothesis

  `jvn : ∀ G : Set (ℝ × Plane), MeasurableSet G →
            (∀ θ ∈ Icc 0 1, ∃ p, (θ,p) ∈ G) →
            ∃ a : ℝ → Plane, AEMeasurable a ∧ ∀ θ ∈ Icc 0 1, (θ, a θ) ∈ G`.

This is the **von Neumann / Jankov–von Neumann measurable uniformization theorem** for a Borel (here
measurable, hence analytic) graph with non-empty sections. It is a genuine mathlib gap (mathlib has the
`AnalyticSet` API and Lusin separation in `MeasureTheory/Constructions/Polish/Basic.lean`, but neither
universal measurability of analytic sets nor a measurable selector).

## Status of this file (WIP — kept out of `src/` so the headline build stays sorry-free)

`lake env lean wip/GeometricMeasureTheory/VonNeumannSelection.lean` kernel-checks it.

What is **proven here** (real down-payments, no `sorry`):
* `analyticSet_exists_nat_nat_range` — a *non-empty* analytic set is literally a continuous image of
  Baire space `ℕ → ℕ` (immediate from the mathlib *definition* of `AnalyticSet`, peeling the empty case);
* `analyticSet_image_isOpen` / `analyticSet_image_cylinder` — the continuous image of an open set (in
  particular a Baire cylinder) is analytic — these are the sets whose `μ`-measurability the leftmost-
  branch selector's measurability is reduced to;
* `jvn_of_measurableSelection` — **the reduction**: the exact `jvn` statement follows from the general
  measurable-selection brick by `X = ℝ, Y = Plane, μ = volume, D = Icc 0 1`. So discharging the brick
  discharges `jvn` and makes `kakeya_aeMeasurable_selection` unconditional.

The lone remaining content is the deep brick `measurableSelection_aemeasurable` (von Neumann selection),
whose proof decomposes — see its docstring — into
  (A) **capacitability**: analytic sets are universally (`NullMeasurable`) measurable [the deep 🟡 core,
      Choquet's theorem via the Souslin operation — the real missing mathlib theory]; and
  (B) the **leftmost-branch uniformizer**: the lexicographically least preimage `σ(x)` of `x` under the
      continuous surjection `F : (ℕ→ℕ) → G`, whose section maps `x ↦ σ(x) n` are measurable w.r.t. the
      σ-algebra generated by analytic sets — hence, by (A), `μ`-`NullMeasurable`, hence `AEMeasurable`.
-/
import Mathlib

open MeasureTheory Set Topology Function
open scoped ENNReal

namespace LeanFormalizations.VonNeumann

/-! ## Foundations (fully proven down-payments toward the von Neumann selector) -/

/-- **A non-empty analytic set is a continuous image of Baire space `ℕ → ℕ`.** This is immediate from
the mathlib *definition* `AnalyticSet s := s = ∅ ∨ ∃ f : (ℕ→ℕ) → α, Continuous f ∧ range f = s`: a
non-empty set rules out the first disjunct. This is the starting representation for the von Neumann
leftmost-branch construction (the parameter space of the selector is exactly this Baire space). -/
theorem analyticSet_exists_nat_nat_range {α : Type*} [TopologicalSpace α] {s : Set α}
    (hs : AnalyticSet s) (hne : s.Nonempty) :
    ∃ f : (ℕ → ℕ) → α, Continuous f ∧ range f = s := by
  rw [AnalyticSet] at hs
  rcases hs with h | h
  · exact absurd h hne.ne_empty
  · exact h

/-- The continuous image of an open set of Baire space is analytic. (`ℕ → ℕ` is Polish, so an open set
is itself Polish, and the continuous image of a Polish space is analytic.) -/
theorem analyticSet_image_isOpen {α : Type*} [TopologicalSpace α] {f : (ℕ → ℕ) → α}
    (hf : Continuous f) {U : Set (ℕ → ℕ)} (hU : IsOpen U) : AnalyticSet (f '' U) :=
  hU.analyticSet_image hf

/-- The continuous image of a Baire cylinder `{σ : ∀ i < n, σ i = x i}` is analytic. These are exactly
the sets `φ(cylinder)` whose `x`-membership predicate the measurability of the leftmost-branch selector
is reduced to (each is analytic, hence `μ`-measurable by capacitability — brick (A)). -/
theorem analyticSet_image_cylinder {α : Type*} [TopologicalSpace α] {f : (ℕ → ℕ) → α}
    (hf : Continuous f) (x : ℕ → ℕ) (n : ℕ) :
    AnalyticSet (f '' (PiNat.cylinder (E := fun _ => ℕ) x n)) :=
  analyticSet_image_isOpen hf (PiNat.isOpen_cylinder (E := fun _ => ℕ) x n)

/-- **Capacitability bridge (fully proven, conditional on capacitability).** If every analytic subset
of `X` is `NullMeasurableSet μ` (the capacitability hypothesis `hcap` — brick A), then any function `g`
that is measurable for the σ-algebra *generated by the analytic sets* is `μ`-a.e.-measurable.

This isolates the role of capacitability precisely: the von Neumann selector `σ` (and hence `a = ψ ∘ σ`)
is `generateFrom {AnalyticSet}`-measurable by construction (its level sets are countable boolean
combinations of analytic `φ '' cylinder` sets), and this bridge converts that into `AEMeasurable`. So
the *only* genuinely-deep input is `hcap` itself (analytic sets are universally measurable).

Proof: `{t | NullMeasurableSet t μ}` is a σ-algebra (`NullMeasurableSet.compl/.iUnion`,
`MeasurableSet.empty.nullMeasurableSet`); `hcap` says it contains every analytic set, so by
`generateFrom_le` it contains `generateFrom {AnalyticSet}`; then `g`-measurability gives each preimage
`NullMeasurableSet`, i.e. `NullMeasurable g μ`, whence `AEMeasurable` (codomain `CountablyGenerated`). -/
theorem aemeasurable_of_generateFrom_analytic
    {X Z : Type*} [TopologicalSpace X] [MeasurableSpace X] (μ : Measure X)
    [MeasurableSpace Z] [MeasurableSpace.CountablyGenerated Z]
    (hcap : ∀ s : Set X, AnalyticSet s → NullMeasurableSet s μ)
    {g : X → Z}
    (hg : @Measurable X Z (MeasurableSpace.generateFrom {s | AnalyticSet s}) _ g) :
    AEMeasurable g μ := by
  -- the σ-algebra of `μ`-null-measurable sets
  let m : MeasurableSpace X :=
    { MeasurableSet' := fun s => NullMeasurableSet s μ
      measurableSet_empty := MeasurableSet.empty.nullMeasurableSet
      measurableSet_compl := fun _ h => h.compl
      measurableSet_iUnion := fun _ h => NullMeasurableSet.iUnion h }
  have hle : MeasurableSpace.generateFrom {s | AnalyticSet s} ≤ m :=
    MeasurableSpace.generateFrom_le (fun t ht => hcap t ht)
  apply NullMeasurable.aemeasurable
  intro s hs
  exact hle _ (hg hs)

/-! ## The deep brick, isolated: a.e.-measurable section of a continuous Baire image

The analytic-representation glue (below) reduces the abstract measurable-selection theorem to the single
irreducible core: selecting an a.e.-measurable point of the fibre of a *continuous* map out of Baire
space. That core is precisely the leftmost-branch construction whose measurability rests on
capacitability — see `exists_aemeasurable_section_of_continuous_range`'s docstring. Everything *around*
it (reduction to the analytic representation, the `jvn` specialization) is proven here with no `sorry`. -/

/-- **Brick A — capacitability (the deep 🟡 core; the genuine missing mathlib theory).** In a Polish
space, every analytic set is `μ`-`NullMeasurable` for any measure `μ`. This is Choquet's capacitability
theorem (analytic sets are universally measurable), classically proved via the Souslin operation /
measures as capacities. mathlib has `AnalyticSet` + Lusin separation but not this. Stated for a general
measure; the only use here is `μ = volume` on `ℝ`. -/
theorem analyticSet_nullMeasurableSet
    {α : Type*} [TopologicalSpace α] [PolishSpace α] [MeasurableSpace α] [BorelSpace α]
    {s : Set α} (hs : AnalyticSet s) (μ : Measure α) : NullMeasurableSet s μ := by
  sorry

/-- **Brick B — the measurable leftmost-branch uniformizer (capacitability-free).** For a *continuous*
`F : (ℕ → ℕ) → X × Y` and `D ⊆ Prod.fst '' range F`, there is a selector `a : X → Y`, *measurable for
the σ-algebra generated by the analytic sets*, with `(x, a x) ∈ range F` for `x ∈ D`.

This is the constructive heart, and it needs NO capacitability — only the analytic structure to land in
`generateFrom {AnalyticSet}`. Construction: `φ := Prod.fst ∘ F`, `ψ := Prod.snd ∘ F`; for `x ∈ D ⊆
range φ` the fibre `φ⁻¹{x}` is closed non-empty; `σ x := ` its lexicographically least element
(recursion via `PiNat.cylinder`, with the level sets of `x ↦ σ x n` being countable boolean
combinations of the analytic `φ '' (cylinder ·)` from `analyticSet_image_cylinder` — hence
`generateFrom {AnalyticSet}`-measurable); `a x := ψ (σ x)` gives `(x, a x) = F (σ x) ∈ range F`.
Reachable from mathlib's `Topology.MetricSpace.PiNat` machinery. -/
theorem exists_generateFrom_analytic_section
    {X Y : Type*} [TopologicalSpace X] [MeasurableSpace X]
    [TopologicalSpace Y] [MeasurableSpace Y] [Nonempty Y]
    {F : (ℕ → ℕ) → X × Y} (hF : Continuous F) {D : Set X}
    (hD : D ⊆ Prod.fst '' (range F)) :
    ∃ a : X → Y, (@Measurable X Y (MeasurableSpace.generateFrom {s | AnalyticSet s}) _ a) ∧
      ∀ x ∈ D, (x, a x) ∈ range F := by
  sorry

/-- **The isolated core, now a PROVEN assembly of bricks A + B via the capacitability bridge.** Given a
continuous `F : (ℕ → ℕ) → X × Y` and `D ⊆ Prod.fst '' range F`, there is a `μ`-a.e.-measurable selector.

Proof: `exists_generateFrom_analytic_section` (brick B) supplies a `generateFrom {AnalyticSet}`-measurable
selector; `analyticSet_nullMeasurableSet` (brick A, capacitability) feeds
`aemeasurable_of_generateFrom_analytic` to upgrade it to `AEMeasurable`. The two genuine difficulties are
now orthogonal and independently attackable. -/
theorem exists_aemeasurable_section_of_continuous_range
    {X Y : Type*} [TopologicalSpace X] [PolishSpace X] [MeasurableSpace X] [BorelSpace X]
    [TopologicalSpace Y] [PolishSpace Y] [MeasurableSpace Y] [BorelSpace Y] [Nonempty Y]
    (μ : Measure X) {F : (ℕ → ℕ) → X × Y} (hF : Continuous F) {D : Set X}
    (hD : D ⊆ Prod.fst '' (range F)) :
    ∃ a : X → Y, AEMeasurable a μ ∧ ∀ x ∈ D, (x, a x) ∈ range F := by
  obtain ⟨a, ha_meas, hsel⟩ := exists_generateFrom_analytic_section hF hD
  refine ⟨a, ?_, hsel⟩
  exact aemeasurable_of_generateFrom_analytic μ
    (fun s hs => analyticSet_nullMeasurableSet hs μ) ha_meas

/-- **Von Neumann / Jankov–von Neumann measurable selection theorem.**

For a measurable graph `G ⊆ X × Y` between standard Borel (Polish) spaces, with non-empty sections over
a set `D ⊆ X`, there is a `μ`-a.e.-measurable selector `a : X → Y` with `(x, a x) ∈ G` for `x ∈ D`.

This is the standard "measurable selection theorem" — citable, Kakeya-agnostic, strictly weaker than the
Π¹₁-uniformization (Kondô) a *pointwise* selector would need.

**Proven here in full** from the isolated core `exists_aemeasurable_section_of_continuous_range`: the
analytic-representation reduction. `G` measurable ⟹ `G` analytic (`MeasurableSet.analyticSet`, on the
Polish + Borel space `X × Y`); if `D = ∅` a constant selector works, else `G` is non-empty and
`analyticSet_exists_nat_nat_range` gives a continuous `F` with `range F = G`, with `D ⊆ Prod.fst ''
range F` from the non-empty sections. Feeding this to the core and rewriting `range F = G` closes it. -/
theorem measurableSelection_aemeasurable
    {X Y : Type*} [TopologicalSpace X] [PolishSpace X] [MeasurableSpace X] [BorelSpace X]
    [TopologicalSpace Y] [PolishSpace Y] [MeasurableSpace Y] [BorelSpace Y] [Nonempty Y]
    (μ : Measure X) {G : Set (X × Y)} (hG : MeasurableSet G) {D : Set X}
    (hsec : ∀ x ∈ D, ∃ y, (x, y) ∈ G) :
    ∃ a : X → Y, AEMeasurable a μ ∧ ∀ x ∈ D, (x, a x) ∈ G := by
  -- handle the empty domain with a constant selector
  rcases D.eq_empty_or_nonempty with hDempty | hDne
  · exact ⟨fun _ => Classical.arbitrary Y, aemeasurable_const, by simp [hDempty]⟩
  -- `D` non-empty ⟹ `G` non-empty
  obtain ⟨x₀, hx₀⟩ := hDne
  obtain ⟨y₀, hy₀⟩ := hsec x₀ hx₀
  have hGne : G.Nonempty := ⟨(x₀, y₀), hy₀⟩
  -- `G` is analytic, hence a continuous image of Baire space
  have hGana : AnalyticSet G := hG.analyticSet
  obtain ⟨F, hFcont, hFrange⟩ := analyticSet_exists_nat_nat_range hGana hGne
  -- the non-empty sections put `D` inside the first-coordinate projection of `range F`
  have hD : D ⊆ Prod.fst '' (range F) := by
    intro x hx
    obtain ⟨y, hy⟩ := hsec x hx
    rw [hFrange]
    exact ⟨(x, y), hy, rfl⟩
  obtain ⟨a, ha, hsel⟩ := exists_aemeasurable_section_of_continuous_range μ hFcont hD
  exact ⟨a, ha, fun x hx => by rw [← hFrange]; exact hsel x hx⟩

/-! ## The reduction: `jvn` from the brick -/

/-- The planar space `ℝ²`, matching `Kakeya2D.Plane`. -/
abbrev Plane : Type := EuclideanSpace ℝ (Fin 2)

/-- **`jvn` follows from the measurable-selection brick.** This is the exact hypothesis consumed by
`Selection.kakeya_aeMeasurable_selection_of_jvn`; supplying it makes the Kakeya a.e.-measurable
selection (the independent second route) unconditional. Specialization `X = ℝ, Y = Plane, μ = volume,
D = Icc 0 1`. -/
theorem jvn_of_measurableSelection
    (G : Set (ℝ × Plane)) (hG : MeasurableSet G)
    (hsec : ∀ θ ∈ Set.Icc (0 : ℝ) 1, ∃ p : Plane, (θ, p) ∈ G) :
    ∃ a : ℝ → Plane, AEMeasurable a ∧ ∀ θ ∈ Set.Icc (0 : ℝ) 1, (θ, a θ) ∈ G :=
  measurableSelection_aemeasurable volume hG hsec

end LeanFormalizations.VonNeumann
