/-
# Toward discharging `jvn`: the von Neumann / Jankov measurable-selection theorem

The planar-Kakeya headline `davies_kakeya_2d` is already complete and axiom-clean via the elementary
open-cover route. This file develops the *independent* second route's missing ingredient: the abstract
measurable selection theorem packaged in `Selection.kakeya_aeMeasurable_selection_of_jvn` as the
hypothesis

  `jvn : ∀ G : Set (ℝ × Plane), MeasurableSet G →
            (∀ θ ∈ Icc 0 1, ∃ p, (θ,p) ∈ G) →
            ∃ a : ℝ → Plane, AEMeasurable a ∧ ∀ θ ∈ Icc 0 1, (θ, a θ) ∈ G`.

This is the **von Neumann / Jankov–von Neumann measurable uniformization theorem** for a Borel (here
measurable, hence analytic) graph with non-empty sections. It is a genuine mathlib gap (mathlib has the
`AnalyticSet` API and Lusin separation in `MeasureTheory/Constructions/Polish/Basic.lean`, but neither
universal measurability of analytic sets nor a measurable selector).

## Status of this file (WIP — kept out of `src/` so the headline build stays sorry-free)

`lake env lean wip/GeometricMeasureTheory/VonNeumannSelection.lean` kernel-checks it.

What is **proven here** (real down-payments, no `sorry`):
* `analyticSet_exists_nat_nat_range` — a *non-empty* analytic set is literally a continuous image of
  Baire space `ℕ → ℕ` (immediate from the mathlib *definition* of `AnalyticSet`, peeling the empty case);
* `analyticSet_image_isOpen` / `analyticSet_image_cylinder` — the continuous image of an open set (in
  particular a Baire cylinder) is analytic — these are the sets whose `μ`-measurability the leftmost-
  branch selector's measurability is reduced to;
* `jvn_of_measurableSelection` — **the reduction**: the exact `jvn` statement follows from the general
  measurable-selection brick by `X = ℝ, Y = Plane, μ = volume, D = Icc 0 1`. So discharging the brick
  discharges `jvn` and makes `kakeya_aeMeasurable_selection` unconditional.

The lone remaining content is the deep brick `measurableSelection_aemeasurable` (von Neumann selection),
whose proof decomposes — see its docstring — into
  (A) **capacitability**: analytic sets are universally (`NullMeasurable`) measurable [the deep 🟡 core,
      Choquet's theorem via the Souslin operation — the real missing mathlib theory]; and
  (B) the **leftmost-branch uniformizer**: the lexicographically least preimage `σ(x)` of `x` under the
      continuous surjection `F : (ℕ→ℕ) → G`, whose section maps `x ↦ σ(x) n` are measurable w.r.t. the
      σ-algebra generated by analytic sets — hence, by (A), `μ`-`NullMeasurable`, hence `AEMeasurable`.
-/
import Mathlib
import GeometricMeasureTheory.Capacitability

open MeasureTheory Set Topology Function
open scoped ENNReal

namespace LeanFormalizations.VonNeumann

/-! ## Foundations (fully proven down-payments toward the von Neumann selector) -/

/-- **A non-empty analytic set is a continuous image of Baire space `ℕ → ℕ`.** This is immediate from
the mathlib *definition* `AnalyticSet s := s = ∅ ∨ ∃ f : (ℕ→ℕ) → α, Continuous f ∧ range f = s`: a
non-empty set rules out the first disjunct. This is the starting representation for the von Neumann
leftmost-branch construction (the parameter space of the selector is exactly this Baire space). -/
theorem analyticSet_exists_nat_nat_range {α : Type*} [TopologicalSpace α] {s : Set α}
    (hs : AnalyticSet s) (hne : s.Nonempty) :
    ∃ f : (ℕ → ℕ) → α, Continuous f ∧ range f = s := by
  rw [AnalyticSet] at hs
  rcases hs with h | h
  · exact absurd h hne.ne_empty
  · exact h

/-- The continuous image of an open set of Baire space is analytic. (`ℕ → ℕ` is Polish, so an open set
is itself Polish, and the continuous image of a Polish space is analytic.) -/
theorem analyticSet_image_isOpen {α : Type*} [TopologicalSpace α] {f : (ℕ → ℕ) → α}
    (hf : Continuous f) {U : Set (ℕ → ℕ)} (hU : IsOpen U) : AnalyticSet (f '' U) :=
  hU.analyticSet_image hf

/-- The continuous image of a Baire cylinder `{σ : ∀ i < n, σ i = x i}` is analytic. These are exactly
the sets `φ(cylinder)` whose `x`-membership predicate the measurability of the leftmost-branch selector
is reduced to (each is analytic, hence `μ`-measurable by capacitability — brick (A)). -/
theorem analyticSet_image_cylinder {α : Type*} [TopologicalSpace α] {f : (ℕ → ℕ) → α}
    (hf : Continuous f) (x : ℕ → ℕ) (n : ℕ) :
    AnalyticSet (f '' (PiNat.cylinder (E := fun _ => ℕ) x n)) :=
  analyticSet_image_isOpen hf (PiNat.isOpen_cylinder (E := fun _ => ℕ) x n)

/-- **Capacitability bridge (fully proven, conditional on capacitability).** If every analytic subset
of `X` is `NullMeasurableSet μ` (the capacitability hypothesis `hcap` — brick A), then any function `g`
that is measurable for the σ-algebra *generated by the analytic sets* is `μ`-a.e.-measurable.

This isolates the role of capacitability precisely: the von Neumann selector `σ` (and hence `a = ψ ∘ σ`)
is `generateFrom {AnalyticSet}`-measurable by construction (its level sets are countable boolean
combinations of analytic `φ '' cylinder` sets), and this bridge converts that into `AEMeasurable`. So
the *only* genuinely-deep input is `hcap` itself (analytic sets are universally measurable).

Proof: `{t | NullMeasurableSet t μ}` is a σ-algebra (`NullMeasurableSet.compl/.iUnion`,
`MeasurableSet.empty.nullMeasurableSet`); `hcap` says it contains every analytic set, so by
`generateFrom_le` it contains `generateFrom {AnalyticSet}`; then `g`-measurability gives each preimage
`NullMeasurableSet`, i.e. `NullMeasurable g μ`, whence `AEMeasurable` (codomain `CountablyGenerated`). -/
theorem aemeasurable_of_generateFrom_analytic
    {X Z : Type*} [TopologicalSpace X] [MeasurableSpace X] (μ : Measure X)
    [MeasurableSpace Z] [MeasurableSpace.CountablyGenerated Z]
    (hcap : ∀ s : Set X, AnalyticSet s → NullMeasurableSet s μ)
    {g : X → Z}
    (hg : @Measurable X Z (MeasurableSpace.generateFrom {s | AnalyticSet s}) _ g) :
    AEMeasurable g μ := by
  -- the σ-algebra of `μ`-null-measurable sets
  let m : MeasurableSpace X :=
    { MeasurableSet' := fun s => NullMeasurableSet s μ
      measurableSet_empty := MeasurableSet.empty.nullMeasurableSet
      measurableSet_compl := fun _ h => h.compl
      measurableSet_iUnion := fun _ h => NullMeasurableSet.iUnion h }
  have hle : MeasurableSpace.generateFrom {s | AnalyticSet s} ≤ m :=
    MeasurableSpace.generateFrom_le (fun t ht => hcap t ht)
  apply NullMeasurable.aemeasurable
  intro s hs
  exact hle _ (hg hs)

/-! ## The deep brick, isolated: a.e.-measurable section of a continuous Baire image

The analytic-representation glue (below) reduces the abstract measurable-selection theorem to the single
irreducible core: selecting an a.e.-measurable point of the fibre of a *continuous* map out of Baire
space. That core is precisely the leftmost-branch construction whose measurability rests on
capacitability — see `exists_aemeasurable_section_of_continuous_range`'s docstring. Everything *around*
it (reduction to the analytic representation, the `jvn` specialization) is proven here with no `sorry`. -/

/-- **Brick A — capacitability (DISCHARGED 2026-06-19; no longer a `sorry`).** In a Polish space,
every analytic set is `μ`-`NullMeasurable` for any **σ-finite** measure `μ`. This is Choquet's
capacitability theorem (analytic sets are universally measurable), classically proved via the Souslin
operation / measures as capacities. mathlib has `AnalyticSet` + Lusin separation but not this; the full
machine-checked proof lives in `GeometricMeasureTheory.Capacitability`
(`LeanFormalizations.Capacitability.analyticSet_nullMeasurableSet`, a self-contained Lusin-scheme
development, `#print axioms` clean), imported here. The `σ`-finiteness hypothesis is harmless: the only
use is `μ = volume` on `ℝ`, which is σ-finite. -/
theorem analyticSet_nullMeasurableSet
    {α : Type*} [TopologicalSpace α] [PolishSpace α] [MeasurableSpace α] [BorelSpace α]
    {s : Set α} (hs : AnalyticSet s) (μ : Measure α) [SigmaFinite μ] : NullMeasurableSet s μ :=
  LeanFormalizations.Capacitability.analyticSet_nullMeasurableSet hs μ

/-- **A branch whose every finite prefix extends into a closed set lies in that set** (pure topology,
no `sorry`). The closedness→membership step of the leftmost-branch construction (brick B): if for every
`n` some `τ ∈ s` agrees with `σ` on `[0, n)`, then the witnesses `τ n → σ` coordinatewise (product
topology), so `σ ∈ s`. Reusable for `exists_generateFrom_analytic_section`. -/
theorem mem_of_forall_prefix_mem {s : Set (ℕ → ℕ)} (hs : IsClosed s) {σ : ℕ → ℕ}
    (h : ∀ n, ∃ τ ∈ s, ∀ i < n, τ i = σ i) : σ ∈ s := by
  choose τ hτs hτ using h
  have htend : Filter.Tendsto τ Filter.atTop (𝓝 σ) := by
    rw [tendsto_pi_nhds]
    intro i
    refine tendsto_const_nhds.congr' ?_
    filter_upwards [Filter.eventually_gt_atTop i] with n hn
    exact (hτ n i hn).symm
  exact hs.mem_of_tendsto htend (Filter.Eventually.of_forall hτs)

/-! ### Brick B, constructed: the explicit leftmost branch (construction PROVEN, measurability isolated)

`cylL w` is the cylinder of a finite prefix `w : List ℕ`; `Wlist φ x n` is the lexicographically least
length-`n` prefix `w` with `x ∈ φ '' cylL w`, built greedily; `branchN φ x n` is its `n`-th entry. The
construction is proven below with NO `sorry`: `phi_branchN` shows `φ (branchN φ x ·) = x` for
`x ∈ range φ`. The ONLY remaining hole in brick B is `measurable_branchN` (the branch is
`generateFrom {AnalyticSet}`-measurable) — the measurability induction. -/

/-- Cylinder of a finite prefix `w : List ℕ` inside Baire space. -/
def cylL (w : List ℕ) : Set (ℕ → ℕ) := {τ | ∀ i, ∀ h : i < w.length, τ i = w.get ⟨i, h⟩}

/-- Greedy leftmost length-`n` prefix of `x` under `φ`: at each step append the least extension that
keeps `x` in the image of the prefix cylinder. -/
noncomputable def Wlist {X : Type*} (φ : (ℕ → ℕ) → X) (x : X) : ℕ → List ℕ
  | 0 => []
  | (n + 1) => Wlist φ x n ++ [sInf {k | x ∈ φ '' cylL (Wlist φ x n ++ [k])}]

/-- The `n`-th entry of the greedy leftmost branch. -/
noncomputable def branchN {X : Type*} (φ : (ℕ → ℕ) → X) (x : X) (n : ℕ) : ℕ :=
  sInf {k | x ∈ φ '' cylL (Wlist φ x n ++ [k])}

theorem Wlist_succ {X : Type*} (φ : (ℕ → ℕ) → X) (x : X) (n : ℕ) :
    Wlist φ x (n + 1) = Wlist φ x n ++ [branchN φ x n] := rfl

theorem Wlist_length {X : Type*} (φ : (ℕ → ℕ) → X) (x : X) (n : ℕ) :
    (Wlist φ x n).length = n := by
  induction n with
  | zero => rfl
  | succ n ih => simp [Wlist, ih]

theorem Wlist_getElem? {X : Type*} (φ : (ℕ → ℕ) → X) (x : X) :
    ∀ n i, i < n → (Wlist φ x n)[i]? = some (branchN φ x i) := by
  intro n
  induction n with
  | zero => intro i hi; exact absurd hi (Nat.not_lt_zero i)
  | succ n ih =>
    intro i hi; rw [Wlist_succ]
    rcases Nat.lt_succ_iff_lt_or_eq.mp hi with h | h
    · rw [List.getElem?_append_left (by rw [Wlist_length]; exact h)]; exact ih i h
    · subst h; rw [List.getElem?_append_right (by rw [Wlist_length])]; simp [Wlist_length]

theorem cylL_nil : cylL [] = (Set.univ : Set (ℕ → ℕ)) := by ext τ; simp [cylL]

/-- A point of `cylL (Wlist φ x n)` also lies in the one-step-longer cylinder using its own `n`-th
coordinate as the extension. -/
theorem mem_cylL_extend {X : Type*} (φ : (ℕ → ℕ) → X) (x : X) (n : ℕ) {τ : ℕ → ℕ}
    (hτ : τ ∈ cylL (Wlist φ x n)) : τ ∈ cylL (Wlist φ x n ++ [τ n]) := by
  intro i hi
  have hlen : (Wlist φ x n ++ [τ n]).length = n + 1 := by simp [Wlist_length]
  have hi' : i < n + 1 := by rw [hlen] at hi; exact hi
  rw [List.get_eq_getElem]
  rcases Nat.lt_succ_iff_lt_or_eq.mp hi' with h | h
  · have hh : i < (Wlist φ x n).length := by rw [Wlist_length]; exact h
    rw [List.getElem_append_left hh]; have := hτ i hh; rwa [List.get_eq_getElem] at this
  · subst h; rw [List.getElem_append_right (by rw [Wlist_length])]; simp [Wlist_length]

/-- **Extendability invariant:** for `x ∈ range φ`, every greedy prefix `Wlist φ x n` keeps `x` in the
image of its cylinder. The `sInf` is always over a non-empty set, so the greedy step is well-defined. -/
theorem mem_image_cylL_Wlist {X : Type*} (φ : (ℕ → ℕ) → X) {x : X} (hx : x ∈ Set.range φ) :
    ∀ n, x ∈ φ '' cylL (Wlist φ x n) := by
  intro n
  induction n with
  | zero => rw [Wlist, cylL_nil, Set.image_univ]; exact hx
  | succ n ih =>
    obtain ⟨τ, hτcyl, hτx⟩ := ih
    have hSne : {k | x ∈ φ '' cylL (Wlist φ x n ++ [k])}.Nonempty :=
      ⟨τ n, τ, mem_cylL_extend φ x n hτcyl, hτx⟩
    have h2 : branchN φ x n ∈ {k | x ∈ φ '' cylL (Wlist φ x n ++ [k])} := Nat.sInf_mem hSne
    rwa [Wlist_succ]

/-- Each greedy prefix is realised by some genuine `φ`-preimage of `x` agreeing with the branch. -/
theorem branch_prefix {X : Type*} (φ : (ℕ → ℕ) → X) {x : X} (hx : x ∈ Set.range φ) (n : ℕ) :
    ∃ τ, φ τ = x ∧ ∀ i < n, τ i = branchN φ x i := by
  obtain ⟨τ, hτcyl, hτx⟩ := mem_image_cylL_Wlist φ hx n
  refine ⟨τ, hτx, fun i hi => ?_⟩
  have hh : i < (Wlist φ x n).length := by rw [Wlist_length]; exact hi
  have e1 : τ i = (Wlist φ x n)[i] := by have := hτcyl i hh; rwa [List.get_eq_getElem] at this
  have e2 : (Wlist φ x n)[i]? = some (branchN φ x i) := Wlist_getElem? φ x n i hi
  rw [List.getElem?_eq_getElem hh] at e2
  rw [e1, Option.some_inj.mp e2]

/-- **Construction (no `sorry`):** the greedy leftmost branch lands in the fibre, i.e.
`φ (branchN φ x ·) = x` for every `x ∈ range φ`. Closedness of the fibre (`φ` continuous, `{x}` closed
in a `T1` space) plus `mem_of_forall_prefix_mem`. -/
theorem phi_branchN {X : Type*} [TopologicalSpace X] [T1Space X] (φ : (ℕ → ℕ) → X)
    (hφ : Continuous φ) {x : X} (hx : x ∈ Set.range φ) : φ (fun n => branchN φ x n) = x := by
  have hclosed : IsClosed (φ ⁻¹' {x}) := isClosed_singleton.preimage hφ
  have hmem : (fun n => branchN φ x n) ∈ φ ⁻¹' {x} :=
    mem_of_forall_prefix_mem hclosed (fun n => branch_prefix φ hx n)
  simpa using hmem

/-- For a fixed prefix `w` of length `n`, the greedy-prefix fibre `{Wlist φ x n = w}` is cut out by the
first `n` branch coordinates — this is what makes the fibre `generateFrom {AnalyticSet}`-measurable by
induction. Proven via `List.ext_getElem?` (`getElem?`, proof-free) + `Wlist_getElem?`. -/
theorem Wlist_eq_iff {X : Type*} (φ : (ℕ → ℕ) → X) (x : X) (n : ℕ) (w : List ℕ)
    (hwlen : w.length = n) :
    Wlist φ x n = w ↔ ∀ i : Fin n, branchN φ x (i : ℕ) = w[(i : ℕ)]'(by rw [hwlen]; exact i.2) := by
  constructor
  · intro hW i
    have h := Wlist_getElem? φ x n i i.2
    rw [hW, List.getElem?_eq_getElem (by rw [hwlen]; exact i.2)] at h
    exact (Option.some_inj.mp h).symm
  · intro h
    apply List.ext_getElem?
    intro i
    by_cases hi : i < n
    · rw [Wlist_getElem? φ x n i hi,
        List.getElem?_eq_getElem (show i < w.length by rw [hwlen]; exact hi)]
      exact congrArg some (h ⟨i, hi⟩)
    · rw [List.getElem?_eq_none (by rw [Wlist_length]; omega),
        List.getElem?_eq_none (by rw [hwlen]; omega)]

/-- A single-coordinate constraint set is open in Baire space (`ℕ` is discrete). -/
theorem isOpen_coord (i c : ℕ) : IsOpen {τ : ℕ → ℕ | τ i = c} := by
  have h : {τ : ℕ → ℕ | τ i = c} = (fun p : ℕ → ℕ => p i) ⁻¹' {c} := rfl
  rw [h]; exact (isOpen_discrete _).preimage (continuous_apply i)

/-- The finite-prefix cylinder `cylL w` is open (finite intersection of single-coordinate sets). -/
theorem isOpen_cylL (w : List ℕ) : IsOpen (cylL w) := by
  have hrw : cylL w = ⋂ (i : Fin w.length), {τ : ℕ → ℕ | τ (i : ℕ) = w.get ⟨i, i.2⟩} := by
    ext τ; simp only [cylL, Set.mem_setOf_eq, Set.mem_iInter]
    exact ⟨fun h i => h i i.2, fun h i hi => h ⟨i, hi⟩⟩
  rw [hrw]; exact isOpen_iInter_of_finite (fun i => isOpen_coord _ _)

/-- The image `φ '' cylL w` is an analytic set, hence a generator of `generateFrom {AnalyticSet}`. -/
theorem measurableSet_image_cylL {X : Type*} [TopologicalSpace X] [MeasurableSpace X]
    {φ : (ℕ → ℕ) → X} (hφ : Continuous φ) (w : List ℕ) :
    @MeasurableSet X (MeasurableSpace.generateFrom {s | AnalyticSet s}) (φ '' cylL w) :=
  MeasurableSpace.measurableSet_generateFrom ((isOpen_cylL w).analyticSet_image hφ)

/-- If each `B j` is `m`-measurable, then `x ↦ sInf {j | x ∈ B j}` is `m`-measurable (its level sets are
countable boolean combinations of the `B j`). The level-set engine behind the branch's measurability. -/
theorem measurable_sInf_indices {X : Type*} (m : MeasurableSpace X) {B : ℕ → Set X}
    (hB : ∀ j, @MeasurableSet X m (B j)) :
    @Measurable X ℕ m _ (fun x => sInf {j | x ∈ B j}) := by
  apply measurable_to_countable'
  intro k
  show @MeasurableSet X m _
  rcases Nat.eq_zero_or_pos k with hk | hk
  · subst hk
    have hset : (fun x => sInf {j | x ∈ B j}) ⁻¹' {0} = B 0 ∪ ⋂ j, (B j)ᶜ := by
      ext x
      simp only [Set.mem_preimage, Set.mem_singleton_iff, Set.mem_union, Set.mem_iInter,
        Set.mem_compl_iff]
      rw [Nat.sInf_eq_zero]
      constructor
      · rintro (h | h)
        · exact Or.inl h
        · refine Or.inr fun j hj => ?_
          exact absurd (show j ∈ {j | x ∈ B j} from hj) (by rw [h]; simp)
      · rintro (h | h)
        · exact Or.inl h
        · refine Or.inr ?_
          ext j
          simp only [Set.mem_setOf_eq, Set.mem_empty_iff_false, iff_false]
          exact h j
    rw [hset]; exact (hB 0).union (MeasurableSet.iInter fun j => (hB j).compl)
  · have hset : (fun x => sInf {j | x ∈ B j}) ⁻¹' {k} = B k ∩ ⋂ (j : ℕ) (_ : j < k), (B j)ᶜ := by
      ext x
      simp only [Set.mem_preimage, Set.mem_singleton_iff, Set.mem_inter_iff, Set.mem_iInter,
        Set.mem_compl_iff]
      constructor
      · intro h
        have hne : {j | x ∈ B j}.Nonempty := by
          by_contra hcon
          rw [Set.not_nonempty_iff_eq_empty] at hcon
          rw [hcon, Nat.sInf_empty] at h; omega
        have hmem : k ∈ {j | x ∈ B j} := h ▸ Nat.sInf_mem hne
        refine ⟨hmem, fun j hj hjB => ?_⟩
        have := Nat.sInf_le (show j ∈ {j | x ∈ B j} from hjB); rw [h] at this; omega
      · rintro ⟨hk', hlt⟩
        have hne : {j | x ∈ B j}.Nonempty := ⟨k, hk'⟩
        refine le_antisymm (Nat.sInf_le hk') ?_
        by_contra hc; rw [not_le] at hc; exact hlt _ hc (Nat.sInf_mem hne)
    rw [hset]
    exact (hB k).inter (MeasurableSet.iInter fun j => MeasurableSet.iInter fun _ => (hB j).compl)

/-- **Brick B's measurability, PROVEN.** `x ↦ branchN φ x n` is `generateFrom {AnalyticSet}`-measurable:
strong induction on `n`, the fibre `{Wlist φ x n = w}` being measurable by `Wlist_eq_iff` + the IH, and
`branchN φ x n` on that fibre being `sInf {k | x ∈ φ '' cylL (w ++ [k])}` (measurable via
`measurable_sInf_indices` + `measurableSet_image_cylL`). With `phi_branchN` this fully discharges
brick B; the whole `jvn` route now rests on capacitability (`analyticSet_nullMeasurableSet`) alone. -/
theorem measurable_branchN {X : Type*} [TopologicalSpace X] [MeasurableSpace X]
    {φ : (ℕ → ℕ) → X} (hφ : Continuous φ) :
    @Measurable X (ℕ → ℕ) (MeasurableSpace.generateFrom {s | AnalyticSet s}) _
      (fun x => fun n => branchN φ x n) := by
  set 𝒜 : MeasurableSpace X := MeasurableSpace.generateFrom {s | AnalyticSet s} with h𝒜
  rw [measurable_pi_iff]
  intro n
  induction n using Nat.strong_induction_on with
  | _ n IH =>
    have hfiber : ∀ w : List ℕ, @MeasurableSet X 𝒜 {x | Wlist φ x n = w} := by
      intro w
      by_cases hwlen : w.length = n
      · have heq : {x | Wlist φ x n = w} =
            ⋂ (i : Fin n), {x | branchN φ x (i : ℕ) = w[(i : ℕ)]'(by rw [hwlen]; exact i.2)} := by
          ext x; simp only [Set.mem_setOf_eq, Set.mem_iInter]; exact Wlist_eq_iff φ x n w hwlen
        rw [heq]
        exact MeasurableSet.iInter fun i => IH (i : ℕ) i.2 (measurableSet_singleton _)
      · have he : {x | Wlist φ x n = w} = ∅ := by
          ext x; simp only [Set.mem_setOf_eq, Set.mem_empty_iff_false, iff_false]
          intro hW; exact hwlen (by rw [← hW, Wlist_length])
        rw [he]; exact MeasurableSet.empty
    apply measurable_to_countable'
    intro c
    show @MeasurableSet X 𝒜 _
    have hunion : (fun x => branchN φ x n) ⁻¹' {c} =
        ⋃ (w : List ℕ), ({x | Wlist φ x n = w} ∩
          {x | sInf {k | x ∈ φ '' cylL (w ++ [k])} = c}) := by
      ext x
      simp only [Set.mem_preimage, Set.mem_singleton_iff, Set.mem_iUnion, Set.mem_inter_iff,
        Set.mem_setOf_eq]
      constructor
      · intro h; exact ⟨Wlist φ x n, rfl, by rw [← h, branchN]⟩
      · rintro ⟨w, hW, hg⟩; rw [branchN, hW]; exact hg
    rw [hunion]
    exact MeasurableSet.iUnion fun w => (hfiber w).inter
      (measurable_sInf_indices 𝒜 (fun k => measurableSet_image_cylL hφ (w ++ [k]))
        (measurableSet_singleton c))

/-- **Brick B — the measurable leftmost-branch uniformizer (capacitability-free), now a PROVEN assembly**
of the explicit construction (`phi_branchN`) and the lone measurability hole (`measurable_branchN`). For
continuous `F : (ℕ → ℕ) → X × Y` and `D ⊆ Prod.fst '' range F`, there is a selector `a : X → Y`,
measurable for `generateFrom {AnalyticSet}`, with `(x, a x) ∈ range F` for `x ∈ D`.

`a x := ψ (branchN φ x ·)` with `φ = Prod.fst ∘ F`, `ψ = Prod.snd ∘ F`; `phi_branchN` gives
`φ (branch) = x`, so `(x, a x) = F (branch) ∈ range F`; measurability is `ψ` (continuous) composed with
the `generateFrom {AnalyticSet}`-measurable branch. -/
theorem exists_generateFrom_analytic_section
    {X Y : Type*} [TopologicalSpace X] [T1Space X] [MeasurableSpace X]
    [TopologicalSpace Y] [MeasurableSpace Y] [BorelSpace Y] [Nonempty Y]
    {F : (ℕ → ℕ) → X × Y} (hF : Continuous F) {D : Set X}
    (hD : D ⊆ Prod.fst '' (range F)) :
    ∃ a : X → Y, (@Measurable X Y (MeasurableSpace.generateFrom {s | AnalyticSet s}) _ a) ∧
      ∀ x ∈ D, (x, a x) ∈ range F := by
  set φ : (ℕ → ℕ) → X := fun σ => (F σ).1 with hφdef
  set ψ : (ℕ → ℕ) → Y := fun σ => (F σ).2 with hψdef
  have hφc : Continuous φ := continuous_fst.comp hF
  have hψc : Continuous ψ := continuous_snd.comp hF
  have hproj : Prod.fst '' range F = range φ := by rw [← Set.range_comp]; rfl
  refine ⟨fun x => ψ (fun n => branchN φ x n), ?_, ?_⟩
  · exact hψc.measurable.comp (measurable_branchN hφc)
  · intro x hx
    have hxr : x ∈ range φ := by rw [← hproj]; exact hD hx
    have hb : φ (fun n => branchN φ x n) = x := phi_branchN φ hφc hxr
    have hF' : F (fun n => branchN φ x n) = (x, ψ (fun n => branchN φ x n)) :=
      Prod.ext hb rfl
    rw [← hF']; exact mem_range_self _

/-- **The isolated core, now a PROVEN assembly of bricks A + B via the capacitability bridge.** Given a
continuous `F : (ℕ → ℕ) → X × Y` and `D ⊆ Prod.fst '' range F`, there is a `μ`-a.e.-measurable selector.

Proof: `exists_generateFrom_analytic_section` (brick B) supplies a `generateFrom {AnalyticSet}`-measurable
selector; `analyticSet_nullMeasurableSet` (brick A, capacitability) feeds
`aemeasurable_of_generateFrom_analytic` to upgrade it to `AEMeasurable`. The two genuine difficulties are
now orthogonal and independently attackable. -/
theorem exists_aemeasurable_section_of_continuous_range
    {X Y : Type*} [TopologicalSpace X] [PolishSpace X] [MeasurableSpace X] [BorelSpace X]
    [TopologicalSpace Y] [PolishSpace Y] [MeasurableSpace Y] [BorelSpace Y] [Nonempty Y]
    (μ : Measure X) [SigmaFinite μ] {F : (ℕ → ℕ) → X × Y} (hF : Continuous F) {D : Set X}
    (hD : D ⊆ Prod.fst '' (range F)) :
    ∃ a : X → Y, AEMeasurable a μ ∧ ∀ x ∈ D, (x, a x) ∈ range F := by
  obtain ⟨a, ha_meas, hsel⟩ := exists_generateFrom_analytic_section hF hD
  refine ⟨a, ?_, hsel⟩
  exact aemeasurable_of_generateFrom_analytic μ
    (fun s hs => analyticSet_nullMeasurableSet hs μ) ha_meas

/-- **Von Neumann / Jankov–von Neumann measurable selection theorem.**

For a measurable graph `G ⊆ X × Y` between standard Borel (Polish) spaces, with non-empty sections over
a set `D ⊆ X`, there is a `μ`-a.e.-measurable selector `a : X → Y` with `(x, a x) ∈ G` for `x ∈ D`.

This is the standard "measurable selection theorem" — citable, Kakeya-agnostic, strictly weaker than the
Π¹₁-uniformization (Kondô) a *pointwise* selector would need.

**Proven here in full** from the isolated core `exists_aemeasurable_section_of_continuous_range`: the
analytic-representation reduction. `G` measurable ⟹ `G` analytic (`MeasurableSet.analyticSet`, on the
Polish + Borel space `X × Y`); if `D = ∅` a constant selector works, else `G` is non-empty and
`analyticSet_exists_nat_nat_range` gives a continuous `F` with `range F = G`, with `D ⊆ Prod.fst ''
range F` from the non-empty sections. Feeding this to the core and rewriting `range F = G` closes it. -/
theorem measurableSelection_aemeasurable
    {X Y : Type*} [TopologicalSpace X] [PolishSpace X] [MeasurableSpace X] [BorelSpace X]
    [TopologicalSpace Y] [PolishSpace Y] [MeasurableSpace Y] [BorelSpace Y] [Nonempty Y]
    (μ : Measure X) [SigmaFinite μ] {G : Set (X × Y)} (hG : MeasurableSet G) {D : Set X}
    (hsec : ∀ x ∈ D, ∃ y, (x, y) ∈ G) :
    ∃ a : X → Y, AEMeasurable a μ ∧ ∀ x ∈ D, (x, a x) ∈ G := by
  -- handle the empty domain with a constant selector
  rcases D.eq_empty_or_nonempty with hDempty | hDne
  · exact ⟨fun _ => Classical.arbitrary Y, aemeasurable_const, by simp [hDempty]⟩
  -- `D` non-empty ⟹ `G` non-empty
  obtain ⟨x₀, hx₀⟩ := hDne
  obtain ⟨y₀, hy₀⟩ := hsec x₀ hx₀
  have hGne : G.Nonempty := ⟨(x₀, y₀), hy₀⟩
  -- `G` is analytic, hence a continuous image of Baire space
  have hGana : AnalyticSet G := hG.analyticSet
  obtain ⟨F, hFcont, hFrange⟩ := analyticSet_exists_nat_nat_range hGana hGne
  -- the non-empty sections put `D` inside the first-coordinate projection of `range F`
  have hD : D ⊆ Prod.fst '' (range F) := by
    intro x hx
    obtain ⟨y, hy⟩ := hsec x hx
    rw [hFrange]
    exact ⟨(x, y), hy, rfl⟩
  obtain ⟨a, ha, hsel⟩ := exists_aemeasurable_section_of_continuous_range μ hFcont hD
  exact ⟨a, ha, fun x hx => by rw [← hFrange]; exact hsel x hx⟩

/-! ## The reduction: `jvn` from the brick -/

/-- The planar space `ℝ²`, matching `Kakeya2D.Plane`. -/
abbrev Plane : Type := EuclideanSpace ℝ (Fin 2)

/-- **`jvn` follows from the measurable-selection brick.** This is the exact hypothesis consumed by
`Selection.kakeya_aeMeasurable_selection_of_jvn`; supplying it makes the Kakeya a.e.-measurable
selection (the independent second route) unconditional. Specialization `X = ℝ, Y = Plane, μ = volume,
D = Icc 0 1`. -/
theorem jvn_of_measurableSelection
    (G : Set (ℝ × Plane)) (hG : MeasurableSet G)
    (hsec : ∀ θ ∈ Set.Icc (0 : ℝ) 1, ∃ p : Plane, (θ, p) ∈ G) :
    ∃ a : ℝ → Plane, AEMeasurable a ∧ ∀ θ ∈ Set.Icc (0 : ℝ) 1, (θ, a θ) ∈ G :=
  measurableSelection_aemeasurable volume hG hsec

end LeanFormalizations.VonNeumann
