#!/usr/bin/env -S uv run --quiet --with numpy python3
"""Erdős #385: structure of the bad n (F(n) = n), a calibration model, and a scale-coupling test.

Positions: for n and a >= 1, a is UNBLOCKED if lpf(n - a) > a, and GOOD if unblocked with
n - a composite.  n is bad iff no position is good (iff every unblocked n - a is prime).

Sections:
  1. bad n (regenerated by sieve) and the rigidity corollary: bad n with no prime among
     n - p (p prime, 3 <= p <= y) must have y# | n (DOOR-EXCEPTIONAL-ERDOS-385.md, Lemma R).
  2. calibration: a Cramér-style model P(n bad) = prod over unblocked a < sqrt n of
     P(a-rough number near n is prime), summed per dyadic block vs the actual counts.
  3. residues of n mod small primes, bad vs control (control = all n <= N with n - 1 prime).
  4. scale coupling ("repulsion"): among controls, P(no good a in annulus I and no good a in
     annulus J) / (P(none in I) P(none in J)), annuli (2^(j-1), 2^j].  > 1 means scales fail
     together (conspiracy), < 1 means repulsion.
  5. small-prime kill profile at Tao's level sqrt(h) for each scale h, bad vs control.
  6. quadratic-character bias of the unblocked (hence prime) n - a for bad n vs control.

Usage: erdos385-bad-structure.py [N]   (default 10**6; the largest known bad n is 267680)
"""
import math
import sys

import numpy as np

N = int(sys.argv[1]) if len(sys.argv) > 1 else 10**6
AMAX = int(math.isqrt(N)) + 1


def lpf_sieve(n):
    lpf = np.zeros(n + 1, dtype=np.int64)
    for p in range(2, int(n**0.5) + 1):
        if lpf[p] == 0:
            blk = lpf[p * p :: p]
            blk[blk == 0] = p
    i = np.arange(n + 1)
    m = (lpf == 0) & (i >= 2)
    lpf[m] = i[m]
    return lpf


def primes_upto(n):
    return [p for p in range(2, n + 1) if all(p % d for d in range(2, int(p**0.5) + 1))]


def kronecker(D, m):
    """Kronecker symbol (D/m) for m > 0."""
    if m == 0:
        return 1 if abs(D) == 1 else 0
    res = 1
    while m % 2 == 0:
        m //= 2
        if D % 2 == 0:
            return 0
        res *= 1 if D % 8 in (1, 7) else -1
    a, b = D % m, m
    while a:
        while a % 2 == 0:
            a //= 2
            if b % 8 in (3, 5):
                res = -res
        a, b = b, a
        if a % 4 == 3 and b % 4 == 3:
            res = -res
        a %= b
    return res if b == 1 else 0


lpf = lpf_sieve(N)
idx = np.arange(N + 1)
isprime = (lpf == idx) & (idx >= 2)
PR = primes_upto(AMAX + 10)

# ---- unblocked / good matrices for the control set -------------------------------------------
ctrl = np.nonzero(isprime[: N] )[0] + 1          # n with n - 1 prime
ctrl = ctrl[(ctrl >= 50) & (ctrl <= N)]
sq = np.sqrt(ctrl)
bad_mask = np.ones(len(ctrl), dtype=bool)
J = int(math.log2(AMAX)) + 1
none_good = np.ones((J + 1, len(ctrl)), dtype=bool)      # no good a in annulus j
kill = np.zeros((J + 1, len(ctrl)))                       # survivors of sieve by primes <= sqrt(2^j)
chi_D = [-3, -4, 5, -7, 8, -8, -11, 12, 13]
logp_model = np.zeros(len(ctrl))
mertens = 1.0
pi = 0
for a in range(1, AMAX + 1):
    while pi < len(PR) and PR[pi] <= a:
        mertens *= 1 - 1 / PR[pi]
        pi += 1
    m = ctrl - a
    ok = (m >= 2) & (a < sq)
    mm = np.where(ok, m, 2)
    l = lpf[mm]
    unb = ok & (l > a)
    good = unb & ~isprime[mm]
    bad_mask &= ~good
    j = int(math.log2(a)) + 1 if a > 1 else 0
    none_good[j] &= ~good
    # model: P(a-rough m ~ n is prime) ~ 1/(log n * prod_{q<=a}(1-1/q)), capped at 1
    pp = np.minimum(1.0, 1.0 / (np.log(ctrl) * mertens))
    logp_model += np.where(unb, np.log(pp), 0.0)
    if a <= 2**J:
        for jj in range(max(j, 1), J + 1):
            h = 2**jj
            if a <= h:
                kill[jj] += ok & (l > math.isqrt(h))

bad = ctrl[bad_mask]
print(f"N = {N:,}: controls (n-1 prime, 50 <= n <= N) = {len(ctrl):,}; bad = {len(bad)}; largest = {bad.max()}")

# ---- 1. rigidity corollary --------------------------------------------------------------------
print("\n1. Lemma R check: for each bad n, the least prime p >= 3 with n - p prime, vs y_n = least y with y# > n")
viol = 0
worst = 0
for n in bad:
    yn, prod = 2, 2
    while prod <= n:
        yn = next(p for p in PR if p > yn)
        prod *= yn
    ps = [p for p in PR if 3 <= p <= yn and isprime[n - p]]
    if not ps:
        viol += 1
    else:
        worst = max(worst, ps[0] / yn)
print(f"   bad n with NO prime n - p for primes 3 <= p <= y_n: {viol} (Lemma R predicts 0)")
print(f"   max over bad n of (least such p)/y_n = {worst:.2f}")

# ---- 2. calibration model -----------------------------------------------------------------------
print("\n2. model E[#bad] vs actual, per dyadic block of n (model = sum over controls of prod P(prime))")
pm = np.exp(logp_model)
for k in range(6, int(math.log2(N)) + 1):
    lo, hi = 2**k, 2 ** (k + 1)
    sel = (ctrl >= lo) & (ctrl < hi)
    if sel.any():
        print(f"   [2^{k:>2}, 2^{k+1:>2}): model {pm[sel].sum():8.3f}   actual {int((bad_mask & sel).sum()):>3}")

# ---- 3. residues --------------------------------------------------------------------------------
print("\n3. P(q | n): bad vs control (n - 1 prime forces n != 1 mod q; baseline 1/(q-1))")
for q in [3, 5, 7, 11, 13]:
    print(f"   q={q:>2}: bad {np.mean(bad % q == 0):.2f}   control {np.mean(ctrl % q == 0):.2f}   1/(q-1) {1/(q-1):.2f}")

# ---- 4. scale coupling ------------------------------------------------------------------------
# Stratify by size so every annulus lies below sqrt(n) (otherwise an empty high annulus is
# trivially "no good a" and n-size alone induces correlation), and within n mod 210 so shared
# small-prime residues of n are factored out.
lo4 = 2 ** (2 * (J - 1))
sel = ctrl >= lo4
Jc = J - 1
print(f"\n4. scale coupling among controls with n in [{lo4:,}, N] (annuli j <= {Jc} lie below sqrt n)")
print("   ratio = P(none_I & none_J) / (P(none_I) P(none_J)); raw | within n mod 210 | within (n mod 210, which primes 11..61 divide n)")
print("   P(no good a in annulus j):", " ".join(f"j{j}:{none_good[j][sel].mean():.3f}" for j in range(1, Jc + 1)))
cls = ctrl[sel] % 210
# second stratifier: n mod 210 together with the set of primes 11..61 dividing n (common-cause test)
sm = [q for q in PR if 11 <= q <= 61]
cls2 = cls.astype(np.int64)
for i, q in enumerate(sm):
    cls2 = cls2 + ((ctrl[sel] % q) == 0).astype(np.int64) * (210 << i)
for j1 in range(2, Jc):
    row = []
    for j2 in range(j1 + 1, Jc + 1):
        a1, a2 = none_good[j1][sel], none_good[j2][sel]
        p1, p2, p12 = a1.mean(), a2.mean(), (a1 & a2).mean()
        raw = p12 / (p1 * p2) if p1 * p2 > 0 else float("nan")
        strat = []
        for C in (cls, cls2):
            num = den = 0.0
            for c in np.unique(C):
                m = C == c
                w = m.mean()
                num += w * (a1[m] & a2[m]).mean()
                den += w * a1[m].mean() * a2[m].mean()
            strat.append(num / den if den > 0 else float("nan"))
        row.append(f"j{j2}:{raw:.2f}|{strat[0]:.2f}|{strat[1]:.2f}")
    print(f"   j{j1}: " + " ".join(row))

# 4b. common-cause test via form 2 of the problem: a good a with lpf(n - a) = p > a is
# a = n mod p with floor(n/p) free of primes < p.  Count the "carrier" primes p in (2^(Jc-2), sqrt n]
# with floor(n/p) p-rough; stratifying on that count should absorb the large-scale coupling.
plo = 2 ** (Jc - 2)
ns = ctrl[sel]
carriers = np.zeros(len(ns), dtype=np.int64)
for q in [q for q in PR if q > plo]:
    fl = ns // q
    okq = (q * q < ns) & (ns % q != 0) & (lpf[np.minimum(fl, N)] >= q)
    carriers += okq
cq = np.minimum(carriers // 2, 15)
print(f"4b. carrier primes p in ({plo}, sqrt n] with floor(n/p) p-rough: median {int(np.median(carriers))}")
for (j1, j2) in [(Jc - 2, Jc - 1), (Jc - 1, Jc), (Jc - 2, Jc)]:
    a1, a2 = none_good[j1][sel], none_good[j2][sel]
    num = den = 0.0
    for c in np.unique(cq):
        m = cq == c
        w = m.mean()
        num += w * (a1[m] & a2[m]).mean()
        den += w * a1[m].mean() * a2[m].mean()
    print(f"   j{j1}-j{j2}: raw {(a1 & a2).mean() / (a1.mean() * a2.mean()):.2f}   within carrier-count strata {num / den:.2f}")

# 4c. Tao's repulsion, stated in form 2.  n is good iff some carrier exists: a prime p with
# p^2 <= n... (floor(n/p) >= p), p not dividing n, floor(n/p) free of primes < p.  So bad <=> no
# carrier at any scale, and "repulsion between scales" = negative dependence between
# {no carrier with p in (P, 2P]} for different P.  Measured raw and within n mod 210.
print("4c. carrier dyadic ranges p in (2^(k-1), 2^k]: P(no carrier) and pairwise ratio raw|mod-210|+primes 11..61 dividing n (z = raw Poisson z-score)")
K = int(math.log2(math.isqrt(N))) + 1
Ck = np.zeros((K + 1, len(ns)), dtype=np.int64)
for q in PR:
    if q * q > N:
        break
    fl = ns // q
    okq = (fl >= q) & (ns % q != 0) & (lpf[np.minimum(fl, N)] >= q)
    Ck[int(math.log2(q)) + 1 if q > 1 else 0] += okq
zero = Ck == 0
print("   P(no carrier in range k):", " ".join(f"k{k}:{zero[k].mean():.3f}" for k in range(2, K)))
print("   P(no carrier at all) among these controls:", f"{np.all(zero, axis=0).mean():.2e}")
for k1 in range(2, K - 1):
    row = []
    for k2 in range(k1 + 1, K):
        a1, a2 = zero[k1], zero[k2]
        p1, p2 = a1.mean(), a2.mean()
        if p1 * p2 == 0 or p1 == 1 or p2 == 1:
            row.append(f"k{k2}:-")
            continue
        st = []
        for C in (cls, cls2):
            num = den = 0.0
            for c in np.unique(C):
                m = C == c
                w = m.mean()
                num += w * (a1[m] & a2[m]).mean()
                den += w * a1[m].mean() * a2[m].mean()
            st.append(num / den)
        exp_joint = p1 * p2 * len(ns)
        z = ((a1 & a2).sum() - exp_joint) / math.sqrt(exp_joint)
        row.append(f"k{k2}:{(a1 & a2).mean() / (p1 * p2):.2f}|{st[0]:.2f}|{st[1]:.2f}(z{z:+.0f})")
    print(f"   k{k1}: " + " ".join(row))

# ---- 5. small-prime kill profile ---------------------------------------------------------------
print("\n5. survivors of the sieve by primes <= sqrt(h) in [n-h, n), / (h prod_{q<=sqrt h}(1-1/q)),")
print("   bad n vs controls in [n/2, 2n], only scales h <= sqrt(n) (Tao's Siegel scenario: << 1 at every scale)")
for jj in range(3, J + 1):
    h = 2**jj
    V = np.prod([1 - 1 / q for q in PR if q <= math.isqrt(h)])
    ratios, pcts = [], []
    for n in bad:
        if h * h > n:
            continue
        rb = kill[jj][ctrl == n][0] / (h * V)
        m = (ctrl >= n // 2) & (ctrl <= 2 * n) & (ctrl != n)
        rc = kill[jj][m] / (h * V)
        ratios.append(rb)
        pcts.append(np.mean(rc < rb) + 0.5 * np.mean(rc == rb))
    if ratios:
        print(f"   h=2^{jj:>2}: {len(ratios):>3} bad n   median ratio {np.median(ratios):.2f}   median control-percentile {np.median(pcts):.2f}")

# ---- 6. quadratic-character bias ------------------------------------------------------------------
print("\n6. mean Kronecker (D / n-a) over unblocked a (all prime for bad n), bad vs a 2000-n control sample")
rng = np.random.default_rng(385)
samp = rng.choice(ctrl[ctrl <= 300_000], size=2000, replace=False)
for D in chi_D:
    def mean_chi(ns):
        tot = cnt = 0
        for n in ns:
            for a in range(1, min(AMAX, int(math.isqrt(n)))):
                if lpf[n - a] > a:
                    tot += kronecker(D, int(n - a))
                    cnt += 1
        return tot / max(cnt, 1)
    print(f"   D={D:>3}: bad {mean_chi(bad):+.3f}   control {mean_chi(samp):+.3f}   chi_D(n) mean over bad {np.mean([kronecker(D, int(n)) for n in bad]):+.2f}")
