/-
Copyright (c) 2026 Trevor Morris. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Trevor Morris
-/

/-
# Four and six exponentials, and more of Schanuel

Phase 16.  It continues `Schanuel.lean`: write down what follows from what we believe.

* **Schanuel ⇒ four exponentials.**  Suppose all four `e^{xᵢyⱼ}` are algebraic.  Then
  `λᵢⱼ = xᵢyⱼ` are logarithms of algebraic numbers satisfying `λ₀₀λ₁₁ = λ₀₁λ₁₀`.  Schanuel, applied
  to a `ℚ`-basis of their span, makes that basis algebraically independent (the exponentials are
  algebraic), and the quadratic relation then forces a rank drop contradicting the independence
  of `x` and `y`.  Waldschmidt (2000) Exercise 1.8; Waldschmidt (2023) §2 sketches it with Roy's
  reformulation.  Case analysis on the dimension of `span_ℚ {λᵢⱼ}` (3 or 4) is the expected
  shape.
* **Four exponentials ⇒ `2^t` or `3^t` transcendental** for irrational `t`: take
  `x = (1, t)`, `y = (log 2, log 3)`.  This is formal-conjectures' `two_pow_three_pow_transcendental`.
* **Six exponentials ⇒ (unconditional)**: if `p₁^t, p₂^t, p₃^t` are integers for three distinct
  primes, then `t ∈ ℕ`.  For irrational `t`, use `x = (1, t)` and `y = log pᵢ`
  (`linearIndependent_log_primes`, proved in phase 15).  For rational `t = a/b`, use
  elementary unique factorization.
* **More Schanuel** (`PENDING_WORK.md`, phase 15): `e, e^e, e^{e^e}` algebraically independent;
  `π` together with logs of distinct primes; `e + log 2`.  Reuse the phase-15 toolkit.

**Result (2026-09-29, one lap): all six are proved and `#print axioms`-clean.**  Nothing was
found underivable.  In particular Schanuel ⇒ four exponentials went through, so the phase-15
note calling four exponentials *not* implied by Schanuel is retracted.  The proof is not the
textbook case-analysis on `dim_ℚ span{λᵢⱼ}` with explicit quadratic polynomial identities: the
two working parts are `algebraicIndependent_of_exp_isAlgebraic` (Schanuel says ℚ-linearly
independent logarithms of algebraic numbers are algebraically independent) and
`false_of_algebraicIndependent_mem` (an algebraically independent family of size `n` cannot sit
inside a field generated by fewer than `n` elements).  In every case the relation
`λ₀₀λ₁₁ = λ₀₁λ₁₀` puts one member of a maximal independent subfamily into the *field* generated
by the others by a single division, and the rank obstruction closes it.

Split into named leaves freely.  Frozen: every statement below, every earlier name, all of
`Literature/`.
-/
import LeanFormalizations.Literature.Exponentials
import LeanFormalizations.NumberTheory.Transcendence.Schanuel

namespace LeanFormalizations.Exponentials

open LeanFormalizations.Literature LeanFormalizations.Schanuel
open Complex IntermediateField Algebra Cardinal Set

/-! ## Toolkit -/

/-- Schanuel ⇒ **algebraic independence of logarithms of algebraic numbers**, in the only form
used below: `ℚ`-linearly independent complex numbers whose exponentials are all algebraic are
themselves algebraically independent. -/
theorem algebraicIndependent_of_exp_isAlgebraic (hS : SchanuelConjecture) {n : ℕ}
    (z : Fin n → ℂ) (hz : LinearIndependent ℚ z)
    (he : ∀ i, IsAlgebraic ℚ (Complex.exp (z i))) : AlgebraicIndependent ℚ z := by
  refine algebraicIndependent_of_schanuel hS z hz z ?_
  rintro w (⟨i, rfl⟩ | ⟨i, rfl⟩)
  · exact isAlgebraic_algebraMap (R := IntermediateField.adjoin ℚ (Set.range z)) (A := ℂ)
      ⟨_, subset_adjoin _ _ ⟨i, rfl⟩⟩
  · exact ((he i).tower_top _)

/-- **The rank obstruction.** An algebraically independent family of size `n` cannot live inside
a field generated by fewer than `n` elements (encoded: by a non-injective family `w` of size
`n`). -/
theorem false_of_algebraicIndependent_mem {n : ℕ} {y w : Fin n → ℂ}
    (hy : AlgebraicIndependent ℚ y) (hw : ¬ Function.Injective w)
    (hmem : ∀ i, y i ∈ IntermediateField.adjoin ℚ (Set.range w)) : False := by
  have h1 : (n : Cardinal) ≤ Algebra.trdeg ℚ (IntermediateField.adjoin ℚ (Set.range y)) :=
    hy.le_trdeg_adjoin
  have hstep : ∀ v ∈ Set.range w,
      IsAlgebraic (IntermediateField.adjoin ℚ (Set.range w)) v := by
    rintro v ⟨i, rfl⟩
    exact isAlgebraic_algebraMap (R := IntermediateField.adjoin ℚ (Set.range w)) (A := ℂ)
      ⟨_, subset_adjoin _ _ ⟨i, rfl⟩⟩
  have hgen : ∀ v ∈ Set.range y,
      IsAlgebraic (IntermediateField.adjoin ℚ (Set.range w)) v := by
    rintro v ⟨i, rfl⟩
    exact isAlgebraic_algebraMap (R := IntermediateField.adjoin ℚ (Set.range w)) (A := ℂ)
      ⟨_, hmem i⟩
  have h2 : Algebra.trdeg ℚ (IntermediateField.adjoin ℚ (Set.range y)) ≤
      Algebra.trdeg ℚ (IntermediateField.adjoin ℚ (Set.range w)) :=
    trdeg_le_adjoin_of_forall_isAlgebraic (forall_isAlgebraic_adjoin hgen)
  exact hw (algebraicIndependent_of_le_trdeg_adjoin w (h1.trans h2)).injective

theorem snoc3 (a b c : ℂ) : Fin.snoc ![a, b] c = ![a, b, c] := by
  funext i; fin_cases i <;> rfl

theorem snoc4 (a b c d : ℂ) : Fin.snoc ![a, b, c] d = ![a, b, c, d] := by
  funext i; fin_cases i <;> rfl

/-- Scaling a `ℚ`-linearly independent family by a nonzero complex number. -/
theorem linearIndependent_const_mul {n : ℕ} {v : Fin n → ℂ} (h : LinearIndependent ℚ v) {c : ℂ}
    (hc : c ≠ 0) : LinearIndependent ℚ (fun i => c * v i) := by
  rw [Fintype.linearIndependent_iff] at h ⊢
  intro g hg i
  refine h g ?_ i
  have hz : c * ∑ j, g j • v j = 0 := by
    rw [Finset.mul_sum, ← hg]
    exact Finset.sum_congr rfl fun j _ => by simp [Rat.smul_def]; ring
  exact (mul_eq_zero.1 hz).resolve_left hc

theorem ratCast_mem_adjoin (S : IntermediateField ℚ ℂ) (q : ℚ) : ((q : ℚ) : ℂ) ∈ S := by
  simpa using S.algebraMap_mem q

/-- **The heart of "Schanuel ⇒ four exponentials".**  Four numbers `a, b, c, d` with
`a·d = b·c`, with `a, b` and `a, c` each `ℚ`-linearly independent, cannot all have algebraic
exponentials. -/
theorem false_of_exp_algebraic_of_quad (hS : SchanuelConjecture) {a b c d : ℂ}
    (hab : LinearIndependent ℚ ![a, b]) (hac : LinearIndependent ℚ ![a, c])
    (hrel : a * d = b * c)
    (hea : IsAlgebraic ℚ (Complex.exp a)) (heb : IsAlgebraic ℚ (Complex.exp b))
    (hec : IsAlgebraic ℚ (Complex.exp c)) (hed : IsAlgebraic ℚ (Complex.exp d)) : False := by
  have ha0 : a ≠ 0 := by simpa using hab.ne_zero 0
  -- `a, b` are algebraically independent (Schanuel on the linearly independent pair)
  have hABind : AlgebraicIndependent ℚ ![a, b] :=
    algebraicIndependent_of_exp_isAlgebraic hS _ hab (by intro i; fin_cases i <;> assumption)
  by_cases h3 : LinearIndependent ℚ ![a, b, c]
  · have hABCind : AlgebraicIndependent ℚ ![a, b, c] :=
      algebraicIndependent_of_exp_isAlgebraic hS _ h3 (by intro i; fin_cases i <;> assumption)
    by_cases h4 : LinearIndependent ℚ ![a, b, c, d]
    · -- all four independent: but `d = bc/a` lies in `ℚ(a,b,c)`
      have hABCDind : AlgebraicIndependent ℚ ![a, b, c, d] :=
        algebraicIndependent_of_exp_isAlgebraic hS _ h4 (by intro i; fin_cases i <;> assumption)
      refine false_of_algebraicIndependent_mem hABCDind (w := ![a, b, c, c]) ?_ ?_
      · intro h
        have : (2 : Fin 4) = 3 := h rfl
        simp at this
      · set L := IntermediateField.adjoin ℚ (Set.range ![a, b, c, c]) with hL
        have hma : a ∈ L := subset_adjoin _ _ ⟨0, rfl⟩
        have hmb : b ∈ L := subset_adjoin _ _ ⟨1, rfl⟩
        have hmc : c ∈ L := subset_adjoin _ _ ⟨2, rfl⟩
        have hd : d = b * c / a := by
          rw [eq_div_iff ha0]; linear_combination hrel
        intro i; fin_cases i
        · exact hma
        · exact hmb
        · exact hmc
        · show d ∈ L
          rw [hd]
          exact div_mem (mul_mem hmb hmc) hma
    · -- `d` is a rational combination of `a, b, c`; solve the relation for `c`
      rw [← snoc4, linearIndependent_finSnoc] at h4
      have hdspan : d ∈ Submodule.span ℚ (Set.range ![a, b, c]) := by
        by_contra hn; exact h4 ⟨h3, hn⟩
      obtain ⟨g, hg⟩ := (Submodule.mem_span_range_iff_exists_fun ℚ).1 hdspan
      rw [Fin.sum_univ_three] at hg
      simp only [Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons,
        Matrix.cons_val_two, Matrix.tail_cons, Rat.smul_def] at hg
      -- `hg : ↑(g 0) * a + ↑(g 1) * b + ↑(g 2) * c = d`
      have hden : (g 2 : ℂ) * a - b ≠ 0 := by
        intro h
        have := (LinearIndependent.pair_iff.1 hab) (g 2) (-1) (by
          simp only [Rat.smul_def]; push_cast; linear_combination h)
        simpa using this.2
      have hc : c = -((g 0 : ℂ) * a * a + (g 1 : ℂ) * a * b) / ((g 2 : ℂ) * a - b) := by
        rw [eq_div_iff hden]
        linear_combination hrel + a * hg
      refine false_of_algebraicIndependent_mem hABCind (w := ![a, b, b]) ?_ ?_
      · intro h
        have : (1 : Fin 3) = 2 := h rfl
        simp at this
      · set L := IntermediateField.adjoin ℚ (Set.range ![a, b, b]) with hL
        have hma : a ∈ L := subset_adjoin _ _ ⟨0, rfl⟩
        have hmb : b ∈ L := subset_adjoin _ _ ⟨1, rfl⟩
        intro i; fin_cases i
        · exact hma
        · exact hmb
        · show c ∈ L
          rw [hc]
          exact div_mem
            (neg_mem (add_mem (mul_mem (mul_mem (ratCast_mem_adjoin L (g 0)) hma) hma)
              (mul_mem (mul_mem (ratCast_mem_adjoin L (g 1)) hma) hmb)))
            (sub_mem (mul_mem (ratCast_mem_adjoin L (g 2)) hma) hmb)
  · -- `c = p a + q b`
    rw [← snoc3, linearIndependent_finSnoc] at h3
    have hcspan : c ∈ Submodule.span ℚ (Set.range ![a, b]) := by
      by_contra hn; exact h3 ⟨hab, hn⟩
    obtain ⟨g, hg⟩ := (Submodule.mem_span_range_iff_exists_fun ℚ).1 hcspan
    rw [Fin.sum_univ_two] at hg
    simp only [Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons, Rat.smul_def] at hg
    have hq : (g 1 : ℚ) ≠ 0 := by
      intro h
      have := (LinearIndependent.pair_iff.1 hac) (g 0) (-1) (by
        simp only [Rat.smul_def]; push_cast; rw [h] at hg; push_cast at hg; linear_combination hg)
      simpa using this.2
    by_cases h3' : LinearIndependent ℚ ![a, b, d]
    · have hABDind : AlgebraicIndependent ℚ ![a, b, d] :=
        algebraicIndependent_of_exp_isAlgebraic hS _ h3' (by intro i; fin_cases i <;> assumption)
      refine false_of_algebraicIndependent_mem hABDind (w := ![a, b, b]) ?_ ?_
      · intro h
        have : (1 : Fin 3) = 2 := h rfl
        simp at this
      · set L := IntermediateField.adjoin ℚ (Set.range ![a, b, b]) with hL
        have hma : a ∈ L := subset_adjoin _ _ ⟨0, rfl⟩
        have hmb : b ∈ L := subset_adjoin _ _ ⟨1, rfl⟩
        have hd : d = ((g 0 : ℂ) * a * b + (g 1 : ℂ) * b * b) / a := by
          rw [eq_div_iff ha0]; linear_combination hrel - b * hg
        intro i; fin_cases i
        · exact hma
        · exact hmb
        · show d ∈ L
          rw [hd]
          exact div_mem (add_mem (mul_mem (mul_mem (ratCast_mem_adjoin L (g 0)) hma) hmb)
            (mul_mem (mul_mem (ratCast_mem_adjoin L (g 1)) hmb) hmb)) hma
    · -- `d = u a + v b` too: everything collapses into `ℚ(a,b)` and `b` becomes quadratic over `ℚ(a)`
      rw [← snoc3, linearIndependent_finSnoc] at h3'
      have hdspan : d ∈ Submodule.span ℚ (Set.range ![a, b]) := by
        by_contra hn; exact h3' ⟨hab, hn⟩
      obtain ⟨h, hh⟩ := (Submodule.mem_span_range_iff_exists_fun ℚ).1 hdspan
      rw [Fin.sum_univ_two] at hh
      simp only [Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons, Rat.smul_def] at hh
      set L := IntermediateField.adjoin ℚ ({a} : Set ℂ) with hL
      have hma : a ∈ L := subset_adjoin _ _ rfl
      have hqC : ((g 1 : ℚ) : ℂ) ≠ 0 := by exact_mod_cast hq
      have hquad : b * b = ((h 0 : ℂ) / (g 1 : ℂ)) * (a * a)
          + (((h 1 : ℂ) - (g 0 : ℂ)) / (g 1 : ℂ)) * (a * b) := by
        field_simp
        linear_combination b * hg - a * hh - hrel
      refine not_isAlgebraic_of_algebraicIndependent_pair hABind ?_
      set A : L := ⟨((h 1 : ℂ) - (g 0 : ℂ)) / (g 1 : ℂ) * a,
        mul_mem (div_mem (sub_mem (ratCast_mem_adjoin L (h 1)) (ratCast_mem_adjoin L (g 0)))
          (ratCast_mem_adjoin L (g 1))) hma⟩ with hA
      set B : L := ⟨(h 0 : ℂ) / (g 1 : ℂ) * (a * a),
        mul_mem (div_mem (ratCast_mem_adjoin L (h 0)) (ratCast_mem_adjoin L (g 1)))
          (mul_mem hma hma)⟩ with hB
      refine ⟨Polynomial.X ^ 2 - Polynomial.C A * Polynomial.X - Polynomial.C B, ?_, ?_⟩
      · have hm : (Polynomial.X ^ 2 - Polynomial.C A * Polynomial.X - Polynomial.C B :
            Polynomial L).Monic := by monicity!
        exact hm.ne_zero
      · simp only [map_sub, map_mul, map_pow, Polynomial.aeval_X, Polynomial.aeval_C]
        show b ^ 2 - (A : ℂ) * b - (B : ℂ) = 0
        simp only [hA, hB]
        linear_combination hquad

/-- Schanuel ⇒ the four exponentials conjecture. -/
theorem fourExponentials_of_schanuel (hS : SchanuelConjecture) : FourExponentialsConjecture := by
  intro x y hx hy
  by_contra hcon
  simp only [Transcendental, not_exists, not_not] at hcon
  have hab : LinearIndependent ℚ ![x 0 * y 0, x 0 * y 1] := by
    have h := linearIndependent_const_mul hy (c := x 0) (hx.ne_zero 0)
    have he : (fun i => x 0 * y i) = ![x 0 * y 0, x 0 * y 1] := by
      funext i; fin_cases i <;> rfl
    rwa [he] at h
  have hac : LinearIndependent ℚ ![x 0 * y 0, x 1 * y 0] := by
    have h := linearIndependent_const_mul hx (c := y 0) (hy.ne_zero 0)
    have he : (fun i => y 0 * x i) = ![x 0 * y 0, x 1 * y 0] := by
      funext i; fin_cases i <;> simp [mul_comm]
    rwa [he] at h
  exact false_of_exp_algebraic_of_quad hS hab hac (by ring)
    (hcon 0 0) (hcon 0 1) (hcon 1 0) (hcon 1 1)


/-- Schanuel ⇒ `log 2` is transcendental (the `n = 1` case of the prime logarithms). -/
theorem transcendental_log_two (hS : SchanuelConjecture) : Transcendental ℚ (Real.log 2) := by
  have h := (algebraicIndependent_log_primes hS ![(⟨2, Nat.prime_two⟩ : Nat.Primes)]
    (fun i j _ => Subsingleton.elim i j)).transcendental 0
  simpa using h

/-- Schanuel ⇒ `e` and `log 2` are algebraically independent, complex form: `z = (1, log 2)`,
exponentials `e` and `2`. -/
theorem algebraicIndependent_exp_one_log_two_complex (hS : SchanuelConjecture) :
    AlgebraicIndependent ℚ ![Complex.exp 1, ((Real.log 2 : ℝ) : ℂ)] := by
  refine algebraicIndependent_of_schanuel hS ![1, ((Real.log 2 : ℝ) : ℂ)]
    (linearIndependent_one_ofReal (transcendental_log_two hS).irrational) _ ?_
  set L := IntermediateField.adjoin ℚ
    (Set.range ![Complex.exp 1, ((Real.log 2 : ℝ) : ℂ)]) with hL
  have hmE : Complex.exp 1 ∈ L := subset_adjoin _ _ ⟨0, rfl⟩
  have hmG : ((Real.log 2 : ℝ) : ℂ) ∈ L := subset_adjoin _ _ ⟨1, rfl⟩
  rintro w (⟨i, rfl⟩ | ⟨i, rfl⟩)
  · fin_cases i
    · exact isAlgebraic_one
    · exact isAlgebraic_algebraMap (R := L) (A := ℂ) ⟨_, hmG⟩
  · fin_cases i
    · exact isAlgebraic_algebraMap (R := L) (A := ℂ) ⟨_, hmE⟩
    · show IsAlgebraic _ (Complex.exp ((Real.log 2 : ℝ) : ℂ))
      have h2 : Complex.exp ((Real.log 2 : ℝ) : ℂ) = (2 : ℂ) := by
        rw [← Complex.ofReal_exp, Real.exp_log (by norm_num)]; norm_num
      rw [h2]
      exact (isAlgebraic_algebraMap (R := ℚ) (A := ℂ) 2).tower_top _

/-- Schanuel ⇒ `e + log 2` is transcendental. -/
theorem transcendental_exp_one_add_log_two' (hS : SchanuelConjecture) :
    Transcendental ℚ (Real.exp 1 + Real.log 2) := by
  intro h
  refine not_isAlgebraic_of_algebraicIndependent_pair
    (algebraicIndependent_exp_one_log_two_complex hS) ?_
  have hC : IsAlgebraic ℚ (Complex.exp 1 + ((Real.log 2 : ℝ) : ℂ)) := by
    simpa [Complex.ofReal_exp] using isAlgebraic_complex_of_real h
  have hrw : ((Real.log 2 : ℝ) : ℂ)
      = (Complex.exp 1 + ((Real.log 2 : ℝ) : ℂ)) - Complex.exp 1 := by ring
  rw [hrw]
  exact isAlgebraic_sub_rat hC isAlgebraic_adjoin_exp_one


/-- `1, e, e^e` are `ℚ`-linearly independent: `e, e^e` are algebraically independent, so they
admit no nontrivial affine relation over `ℚ`. -/
theorem linearIndependent_one_exp_exp_exp (hS : SchanuelConjecture) :
    LinearIndependent ℚ ![(1 : ℂ), ((Real.exp 1 : ℝ) : ℂ), ((Real.exp (Real.exp 1) : ℝ) : ℂ)] := by
  have hind : AlgebraicIndependent ℚ
      ![((Real.exp 1 : ℝ) : ℂ), ((Real.exp (Real.exp 1) : ℝ) : ℂ)] := by
    have h := algebraicIndependent_exp_one_exp_exp_one_complex hS
    have he : Complex.exp ((Real.exp 1 : ℝ) : ℂ) = ((Real.exp (Real.exp 1) : ℝ) : ℂ) := by
      rw [← Complex.ofReal_exp]
    rwa [he] at h
  rw [Fintype.linearIndependent_iff]
  intro g hg
  rw [Fin.sum_univ_three] at hg
  have hrel : (algebraMap ℚ ℂ) (g 0) + ∑ i, (algebraMap ℚ ℂ) (![g 1, g 2] i) *
      ![((Real.exp 1 : ℝ) : ℂ), ((Real.exp (Real.exp 1) : ℝ) : ℂ)] i = 0 := by
    rw [Fin.sum_univ_two]
    simp only [Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons,
      Matrix.cons_val_two, Matrix.tail_cons, Rat.smul_def, eq_ratCast] at hg ⊢
    linear_combination hg
  obtain ⟨h0, hrest⟩ := eq_zero_of_algebraicIndependent_linear hind (g 0) ![g 1, g 2] hrel
  intro i
  fin_cases i
  · exact h0
  · simpa using hrest 0
  · simpa using hrest 1

/-- Schanuel ⇒ `e, e^e, e^{e^e}` algebraically independent, complex form: `z = (1, e, e^e)`. -/
theorem algebraicIndependent_exp_tower_three_complex (hS : SchanuelConjecture) :
    AlgebraicIndependent ℚ ![((Real.exp 1 : ℝ) : ℂ), ((Real.exp (Real.exp 1) : ℝ) : ℂ),
      ((Real.exp (Real.exp (Real.exp 1)) : ℝ) : ℂ)] := by
  refine algebraicIndependent_of_schanuel hS _ (linearIndependent_one_exp_exp_exp hS) _ ?_
  set L := IntermediateField.adjoin ℚ (Set.range
    ![((Real.exp 1 : ℝ) : ℂ), ((Real.exp (Real.exp 1) : ℝ) : ℂ),
      ((Real.exp (Real.exp (Real.exp 1)) : ℝ) : ℂ)]) with hL
  have m0 : ((Real.exp 1 : ℝ) : ℂ) ∈ L := subset_adjoin _ _ ⟨0, rfl⟩
  have m1 : ((Real.exp (Real.exp 1) : ℝ) : ℂ) ∈ L := subset_adjoin _ _ ⟨1, rfl⟩
  have m2 : ((Real.exp (Real.exp (Real.exp 1)) : ℝ) : ℂ) ∈ L := subset_adjoin _ _ ⟨2, rfl⟩
  have e0 : Complex.exp 1 = ((Real.exp 1 : ℝ) : ℂ) := by simp
  have e1 : Complex.exp ((Real.exp 1 : ℝ) : ℂ) = ((Real.exp (Real.exp 1) : ℝ) : ℂ) := by
    rw [← Complex.ofReal_exp]
  have e2 : Complex.exp ((Real.exp (Real.exp 1) : ℝ) : ℂ)
      = ((Real.exp (Real.exp (Real.exp 1)) : ℝ) : ℂ) := by rw [← Complex.ofReal_exp]
  rintro w (⟨i, rfl⟩ | ⟨i, rfl⟩)
  · fin_cases i
    · exact isAlgebraic_one
    · exact isAlgebraic_algebraMap (R := L) (A := ℂ) ⟨_, m0⟩
    · exact isAlgebraic_algebraMap (R := L) (A := ℂ) ⟨_, m1⟩
  · fin_cases i
    · show IsAlgebraic _ (Complex.exp 1)
      rw [e0]; exact isAlgebraic_algebraMap (R := L) (A := ℂ) ⟨_, m0⟩
    · show IsAlgebraic _ (Complex.exp ((Real.exp 1 : ℝ) : ℂ))
      rw [e1]; exact isAlgebraic_algebraMap (R := L) (A := ℂ) ⟨_, m1⟩
    · show IsAlgebraic _ (Complex.exp ((Real.exp (Real.exp 1) : ℝ) : ℂ))
      rw [e2]; exact isAlgebraic_algebraMap (R := L) (A := ℂ) ⟨_, m2⟩

theorem algebraicIndependent_exp_tower_three' (hS : SchanuelConjecture) :
    AlgebraicIndependent ℚ
      ![Real.exp 1, Real.exp (Real.exp 1), Real.exp (Real.exp (Real.exp 1))] := by
  refine algebraicIndependent_real_of_complex ?_
  have h := algebraicIndependent_exp_tower_three_complex hS
  have hcomp : (fun i => ((![Real.exp 1, Real.exp (Real.exp 1),
      Real.exp (Real.exp (Real.exp 1))] i : ℝ) : ℂ))
      = ![((Real.exp 1 : ℝ) : ℂ), ((Real.exp (Real.exp 1) : ℝ) : ℂ),
        ((Real.exp (Real.exp (Real.exp 1)) : ℝ) : ℂ)] := by
    funext i; fin_cases i <;> rfl
  rw [hcomp]; exact h


section PiLogPrimes

variable {n : ℕ} (p : Fin n → Nat.Primes)

/-- The Schanuel input for `π` and prime logarithms: `z = (iπ, log p₁, …, log pₙ)`. -/
noncomputable def zPiLog : Fin (n + 1) → ℂ :=
  Fin.cons (Complex.I * (Real.pi : ℂ)) fun i => ((Real.log ((p i : ℕ) : ℝ) : ℝ) : ℂ)

/-- The target family: `π, log p₁, …, log pₙ`, as complex numbers. -/
noncomputable def yPiLog : Fin (n + 1) → ℂ :=
  Fin.cons ((Real.pi : ℝ) : ℂ) fun i => ((Real.log ((p i : ℕ) : ℝ) : ℝ) : ℂ)

/-- `iπ` together with the logarithms of distinct primes is `ℚ`-linearly independent: the
imaginary part isolates the `iπ` coefficient, and unique factorisation does the rest. -/
theorem linearIndependent_zPiLog (hp : Function.Injective p) :
    LinearIndependent ℚ (zPiLog p) := by
  rw [Fintype.linearIndependent_iff]
  intro g hg
  rw [Fin.sum_univ_succ] at hg
  simp only [zPiLog, Fin.cons_zero, Fin.cons_succ, Rat.smul_def] at hg
  have hsum : ∑ i : Fin n, ((g i.succ : ℚ) : ℂ) * ((Real.log ((p i : ℕ) : ℝ) : ℝ) : ℂ)
      = ((∑ i : Fin n, (g i.succ : ℝ) * Real.log ((p i : ℕ) : ℝ) : ℝ) : ℂ) := by
    rw [Complex.ofReal_sum]
    exact Finset.sum_congr rfl fun i _ => by push_cast; ring
  rw [hsum] at hg
  set R : ℝ := ∑ i : Fin n, (g i.succ : ℝ) * Real.log ((p i : ℕ) : ℝ) with hR
  have him := congrArg Complex.im hg
  have hre := congrArg Complex.re hg
  simp at him hre
  have h0 : g 0 = 0 := him
  have hRzero : R = 0 := hre
  have hrest : ∀ i : Fin n, g i.succ = 0 := by
    have := Fintype.linearIndependent_iff.1 (linearIndependent_log_primes p hp)
      (fun i => g i.succ) (by simpa [Rat.smul_def, hR] using hRzero)
    exact this
  intro i
  refine Fin.cases ?_ (fun j => hrest j) i
  exact h0


/-- Schanuel ⇒ `π` and the logarithms of distinct primes are algebraically independent,
complex form: `z = (iπ, log p₁, …, log pₙ)`, exponentials `−1, p₁, …, pₙ`. -/
theorem algebraicIndependent_yPiLog (hS : SchanuelConjecture) (hp : Function.Injective p) :
    AlgebraicIndependent ℚ (yPiLog p) := by
  refine algebraicIndependent_of_schanuel hS _ (linearIndependent_zPiLog p hp) (yPiLog p) ?_
  set L := IntermediateField.adjoin ℚ (Set.range (yPiLog p)) with hL
  have mpi : ((Real.pi : ℝ) : ℂ) ∈ L := subset_adjoin _ _ ⟨0, rfl⟩
  have mlog : ∀ i : Fin n, ((Real.log ((p i : ℕ) : ℝ) : ℝ) : ℂ) ∈ L :=
    fun i => subset_adjoin _ _ ⟨i.succ, rfl⟩
  rintro w (⟨i, rfl⟩ | ⟨i, rfl⟩)
  · refine Fin.cases ?_ (fun j => ?_) i
    · show IsAlgebraic _ (Complex.I * (Real.pi : ℂ))
      exact isAlgebraic_mul_rat isAlgebraic_I
        (isAlgebraic_algebraMap (R := L) (A := ℂ) ⟨_, mpi⟩)
    · show IsAlgebraic _ ((Real.log ((p j : ℕ) : ℝ) : ℂ))
      exact isAlgebraic_algebraMap (R := L) (A := ℂ) ⟨_, mlog j⟩
  · refine Fin.cases ?_ (fun j => ?_) i
    · show IsAlgebraic _ (Complex.exp (Complex.I * (Real.pi : ℂ)))
      rw [show Complex.I * (Real.pi : ℂ) = (Real.pi : ℂ) * Complex.I by ring, Complex.exp_mul_I]
      simpa using (isAlgebraic_algebraMap (R := L) (A := ℂ) (-1))
    · show IsAlgebraic _ (Complex.exp ((Real.log ((p j : ℕ) : ℝ) : ℂ)))
      have hpos : (0 : ℝ) < ((p j : ℕ) : ℝ) := by exact_mod_cast (p j).2.pos
      have hx : Complex.exp ((Real.log ((p j : ℕ) : ℝ) : ℂ)) = (((p j : ℕ) : ℝ) : ℂ) := by
        rw [← Complex.ofReal_exp, Real.exp_log hpos]
      rw [hx]
      exact (isAlgebraic_complex_of_real
        (isAlgebraic_algebraMap (R := ℚ) (A := ℝ) ((p j : ℕ) : ℚ))).tower_top _

/-- Schanuel ⇒ `π` together with the logarithms of distinct primes are algebraically
independent. -/
theorem algebraicIndependent_pi_log_primes' (hS : SchanuelConjecture)
    (hp : Function.Injective p) :
    AlgebraicIndependent ℚ
      (Fin.cons Real.pi fun i ↦ Real.log ((p i : ℕ) : ℝ) : Fin (n + 1) → ℝ) := by
  refine algebraicIndependent_real_of_complex ?_
  have hcomp : (fun i => (((Fin.cons Real.pi fun i ↦ Real.log ((p i : ℕ) : ℝ) :
      Fin (n + 1) → ℝ) i : ℝ) : ℂ)) = yPiLog p := by
    funext i
    refine Fin.cases ?_ (fun j => ?_) i <;> rfl
  rw [hcomp]
  exact algebraicIndependent_yPiLog p hS hp

end PiLogPrimes


/-- Transcendence transfers back along `ℝ → ℂ`. -/
theorem transcendental_real_of_complex {r : ℝ} (h : Transcendental ℚ ((r : ℝ) : ℂ)) :
    Transcendental ℚ r := fun hr => h (isAlgebraic_complex_of_real hr)

theorem cexp_mul_ofReal_log {q t : ℝ} (hq : 0 < q) :
    Complex.exp ((t : ℂ) * ((Real.log q : ℝ) : ℂ)) = ((q ^ t : ℝ) : ℂ) := by
  rw [show ((t : ℂ) * ((Real.log q : ℝ) : ℂ)) = ((Real.log q * t : ℝ) : ℂ) by push_cast; ring,
    ← Complex.ofReal_exp, Real.rpow_def_of_pos hq]

theorem linearIndependent_log_two_three :
    LinearIndependent ℚ ![((Real.log 2 : ℝ) : ℂ), ((Real.log 3 : ℝ) : ℂ)] := by
  have hp : Function.Injective
      (![(⟨2, Nat.prime_two⟩ : Nat.Primes), ⟨3, Nat.prime_three⟩]) := by decide
  have h := (linearIndependent_log_primes _ hp).map'
    ((IsScalarTower.toAlgHom ℚ ℝ ℂ).toLinearMap)
    (by rw [LinearMap.ker_eq_bot]; exact (IsScalarTower.toAlgHom ℚ ℝ ℂ).injective)
  simp only [Function.comp_def] at h
  have he : (fun i => ((IsScalarTower.toAlgHom ℚ ℝ ℂ).toLinearMap)
      (Real.log (((![(⟨2, Nat.prime_two⟩ : Nat.Primes), ⟨3, Nat.prime_three⟩] i : Nat.Primes)
        : ℕ) : ℝ)))
      = ![((Real.log 2 : ℝ) : ℂ), ((Real.log 3 : ℝ) : ℂ)] := by
    funext i; fin_cases i <;> norm_num
  rwa [he] at h

/-- Four exponentials ⇒ for irrational `t`, `2^t` or `3^t` is transcendental: take
`x = (1, t)` and `y = (log 2, log 3)`.  The two exponentials in the `x = 1` row are `2` and `3`,
so the transcendental one is `2^t` or `3^t`. -/
theorem two_rpow_or_three_rpow_transcendental' (h4 : FourExponentialsConjecture) {t : ℝ}
    (ht : Irrational t) :
    Transcendental ℚ ((2 : ℝ) ^ t) ∨ Transcendental ℚ ((3 : ℝ) ^ t) := by
  obtain ⟨i, j, htr⟩ := h4 ![(1 : ℂ), ((t : ℝ) : ℂ)]
    ![((Real.log 2 : ℝ) : ℂ), ((Real.log 3 : ℝ) : ℂ)]
    (linearIndependent_one_ofReal ht) linearIndependent_log_two_three
  fin_cases i <;> fin_cases j <;>
    simp only [Fin.zero_eta, Fin.mk_one, Fin.isValue, Matrix.cons_val_zero, Matrix.cons_val_one,
      Matrix.head_cons, one_mul] at htr
  · exfalso
    refine htr ?_
    rw [← Complex.ofReal_exp, Real.exp_log (by norm_num : (0:ℝ) < 2)]
    simpa using (isAlgebraic_algebraMap (R := ℚ) (A := ℂ) (2 : ℚ))
  · exfalso
    refine htr ?_
    rw [← Complex.ofReal_exp, Real.exp_log (by norm_num : (0:ℝ) < 3)]
    simpa using (isAlgebraic_algebraMap (R := ℚ) (A := ℂ) (3 : ℚ))
  · left
    refine transcendental_real_of_complex ?_
    rwa [cexp_mul_ofReal_log (by norm_num : (0:ℝ) < 2)] at htr
  · right
    refine transcendental_real_of_complex ?_
    rwa [cexp_mul_ofReal_log (by norm_num : (0:ℝ) < 3)] at htr


/-- Four exponentials ⇒ for irrational `t`, `2^t` or `3^t` is transcendental. -/
theorem two_rpow_or_three_rpow_transcendental (h4 : FourExponentialsConjecture) {t : ℝ}
    (ht : Irrational t) :
    Transcendental ℚ ((2 : ℝ) ^ t) ∨ Transcendental ℚ ((3 : ℝ) ^ t) :=
  two_rpow_or_three_rpow_transcendental' h4 ht

/-- `(b^q)^den = b^num` for a positive real base and a rational exponent. -/
theorem rpow_rat_pow_den {b : ℝ} (hb : 0 < b) (q : ℚ) :
    (b ^ (q : ℝ)) ^ (q.den : ℕ) = b ^ (q.num : ℤ) := by
  rw [← Real.rpow_natCast (b ^ (q : ℝ)) q.den, ← Real.rpow_mul hb.le]
  have hmul : (q : ℝ) * ((q.den : ℕ) : ℝ) = (q.num : ℝ) := by
    have hd : ((q.den : ℝ)) ≠ 0 := by exact_mod_cast q.den_nz
    field_simp
    exact_mod_cast congrArg (fun t : ℚ => (t : ℝ)) (Rat.mul_den_eq_num q)
  rw [hmul, Real.rpow_intCast]

/-- **Unique factorisation half**: for a single prime `P`, if `P^q` is a natural number for a
rational `q`, then `q` is a natural number. -/
theorem rat_eq_nat_of_prime_rpow {P : Nat.Primes} {q : ℚ} {m : ℕ}
    (hm : ((P : ℕ) : ℝ) ^ (q : ℝ) = m) : ∃ N : ℕ, q = N := by
  have hP : (1 : ℝ) < ((P : ℕ) : ℝ) := by exact_mod_cast P.2.one_lt
  have hPpos : (0 : ℝ) < ((P : ℕ) : ℝ) := by linarith
  have hpow := rpow_rat_pow_den hPpos q
  rw [hm] at hpow
  -- `m ≥ 1`
  have hm1 : 1 ≤ m := by
    by_contra hlt
    have : m = 0 := by omega
    subst this
    have := Real.rpow_pos_of_pos hPpos (q : ℝ)
    rw [hm] at this
    simp at this
  -- the exponent is nonnegative
  have hnum : 0 ≤ q.num := by
    by_contra hneg
    rw [not_le] at hneg
    have h1 : ((P : ℕ) : ℝ) ^ (q.num : ℤ) < 1 := by
      apply zpow_lt_one_of_neg₀ hP hneg
    have h2 : (1 : ℝ) ≤ ((m : ℕ) : ℝ) ^ (q.den : ℕ) := by
      apply one_le_pow₀
      exact_mod_cast hm1
    rw [← hpow] at h1
    linarith
  set N : ℕ := q.num.toNat with hN
  have hnumN : (q.num : ℤ) = (N : ℤ) := by omega
  have hnatpow : (m : ℕ) ^ (q.den : ℕ) = (P : ℕ) ^ N := by
    have : ((m : ℕ) : ℝ) ^ (q.den : ℕ) = (((P : ℕ) : ℝ)) ^ (N : ℕ) := by
      rw [hpow, hnumN, zpow_natCast]
    exact_mod_cast this
  have hfac := congrArg (fun k : ℕ => k.factorization (P : ℕ)) hnatpow
  simp only [Nat.factorization_pow, Finsupp.smul_apply, smul_eq_mul,
    Nat.Prime.factorization P.2, Finsupp.single_eq_same, mul_one] at hfac
  -- `hfac : q.den * m.factorization P = N`
  have hdvd : q.den ∣ N := ⟨_, hfac.symm⟩
  have hden : q.den = 1 := by
    have : q.den ∣ q.num.natAbs := by
      have : N = q.num.natAbs := by omega
      rwa [this] at hdvd
    exact Nat.Coprime.eq_one_of_dvd q.reduced.symm this
  refine ⟨N, ?_⟩
  have : q = (q.num : ℚ) := by
    rw [← Rat.num_div_den q, hden]; simp
  rw [this, hnumN]
  push_cast
  ring


/-- **Unconditional**, from the six exponentials theorem: if `pᵢ^t` is an integer for three
distinct primes `pᵢ`, then `t` is a natural number.  For irrational `t` the six numbers
`e^{x_i y_j}` with `x = (1, t)`, `y = (log p₁, log p₂, log p₃)` are `p₁, p₂, p₃` and the three
given integers, all algebraic — contradicting the theorem.  For rational `t` one prime and
unique factorisation suffice. -/
theorem eq_nat_of_three_primes_rpow' (h6 : SixExponentials) {t : ℝ} {p : Fin 3 → Nat.Primes}
    (hp : Function.Injective p) (h : ∀ i, ∃ n : ℕ, ((p i : ℕ) : ℝ) ^ t = n) :
    ∃ n : ℕ, t = n := by
  by_cases ht : Irrational t
  · exfalso
    have hy : LinearIndependent ℚ (fun i => ((Real.log ((p i : ℕ) : ℝ) : ℝ) : ℂ)) :=
      (linearIndependent_log_primes p hp).map'
        ((IsScalarTower.toAlgHom ℚ ℝ ℂ).toLinearMap)
        (by rw [LinearMap.ker_eq_bot]; exact (IsScalarTower.toAlgHom ℚ ℝ ℂ).injective)
    obtain ⟨i, j, htr⟩ := h6 ![(1 : ℂ), ((t : ℝ) : ℂ)] _ (linearIndependent_one_ofReal ht) hy
    have hpos : (0 : ℝ) < ((p j : ℕ) : ℝ) := by exact_mod_cast (p j).2.pos
    fin_cases i <;>
      simp only [Fin.zero_eta, Fin.mk_one, Fin.isValue, Matrix.cons_val_zero,
        Matrix.cons_val_one, one_mul] at htr
    · refine htr ?_
      rw [← Complex.ofReal_exp, Real.exp_log hpos]
      exact isAlgebraic_complex_of_real
        (by simpa using isAlgebraic_algebraMap (R := ℚ) (A := ℝ) (((p j : ℕ) : ℚ)))
    · obtain ⟨m, hm⟩ := h j
      refine htr ?_
      rw [cexp_mul_ofReal_log hpos, hm]
      exact isAlgebraic_complex_of_real
        (by simpa using isAlgebraic_algebraMap (R := ℚ) (A := ℝ) ((m : ℚ)))
  · rw [Irrational, not_not] at ht
    obtain ⟨q, hq⟩ := ht
    obtain ⟨m, hm⟩ := h 0
    rw [← hq] at hm
    obtain ⟨N, hN⟩ := rat_eq_nat_of_prime_rpow hm
    exact ⟨N, by rw [← hq, hN]; push_cast; ring⟩


/-- **Unconditional**, from the six exponentials theorem: if `pᵢ^t` is an integer for three
distinct primes `pᵢ`, then `t` is a natural number. -/
theorem eq_nat_of_three_primes_rpow (h6 : SixExponentials) {t : ℝ} {p : Fin 3 → Nat.Primes}
    (hp : Function.Injective p) (h : ∀ i, ∃ n : ℕ, ((p i : ℕ) : ℝ) ^ t = n) :
    ∃ n : ℕ, t = n :=
  eq_nat_of_three_primes_rpow' h6 hp h

/-- Schanuel ⇒ `e, e^e, e^{e^e}` are algebraically independent: take `z = (1, e, e^e)`. -/
theorem algebraicIndependent_exp_tower_three (hS : SchanuelConjecture) :
    AlgebraicIndependent ℚ
      ![Real.exp 1, Real.exp (Real.exp 1), Real.exp (Real.exp (Real.exp 1))] :=
  algebraicIndependent_exp_tower_three' hS

/-- Schanuel ⇒ `π` together with the logarithms of distinct primes are algebraically
independent: take `z = (iπ, log p₁, …, log pₙ)`. -/
theorem algebraicIndependent_pi_log_primes (hS : SchanuelConjecture) {n : ℕ}
    (p : Fin n → Nat.Primes) (hp : Function.Injective p) :
    AlgebraicIndependent ℚ
      (Fin.cons Real.pi fun i ↦ Real.log (p i : ℕ) : Fin (n + 1) → ℝ) :=
  algebraicIndependent_pi_log_primes' p hS hp

/-- Schanuel ⇒ `e + log 2` is transcendental: `e` and `log 2` are algebraically independent,
by taking `z = (1, log 2)`. -/
theorem transcendental_exp_one_add_log_two (hS : SchanuelConjecture) :
    Transcendental ℚ (Real.exp 1 + Real.log 2) :=
  transcendental_exp_one_add_log_two' hS

end LeanFormalizations.Exponentials
