/-
Copyright (c) 2026 Trevor Morris. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Trevor Morris
-/

/-
# Four and six exponentials, and more of Schanuel

Phase 16.  It continues `Schanuel.lean`: write down what follows from what we believe.

* **Schanuel ⇒ four exponentials.**  Suppose all four `e^{xᵢyⱼ}` are algebraic.  Then
  `λᵢⱼ = xᵢyⱼ` are logarithms of algebraic numbers satisfying `λ₀₀λ₁₁ = λ₀₁λ₁₀`.  Schanuel, applied
  to a `ℚ`-basis of their span, makes that basis algebraically independent (the exponentials are
  algebraic), and the quadratic relation then forces a rank drop contradicting the independence
  of `x` and `y`.  Waldschmidt (2000) Exercise 1.8; Waldschmidt (2023) §2 sketches it with Roy's
  reformulation.  Case analysis on the dimension of `span_ℚ {λᵢⱼ}` (3 or 4) is the expected
  shape.
* **Four exponentials ⇒ `2^t` or `3^t` transcendental** for irrational `t`: take
  `x = (1, t)`, `y = (log 2, log 3)`.  This is formal-conjectures' `two_pow_three_pow_transcendental`.
* **Six exponentials ⇒ (unconditional)**: if `p₁^t, p₂^t, p₃^t` are integers for three distinct
  primes, then `t ∈ ℕ`.  For irrational `t`, use `x = (1, t)` and `y = log pᵢ`
  (`linearIndependent_log_primes`, proved in phase 15).  For rational `t = a/b`, use
  elementary unique factorization.
* **More Schanuel** (`PENDING_WORK.md`, phase 15): `e, e^e, e^{e^e}` algebraically independent;
  `π` together with logs of distinct primes; `e + log 2`.  Reuse the phase-15 toolkit.

Split into named leaves freely.  Frozen: every statement below, every earlier name, all of
`Literature/`.
-/
import LeanFormalizations.Literature.Exponentials
import LeanFormalizations.NumberTheory.Transcendence.Schanuel

namespace LeanFormalizations.Exponentials

open LeanFormalizations.Literature LeanFormalizations.Schanuel
open Complex IntermediateField Algebra Cardinal Set

/-! ## Toolkit -/

/-- Schanuel ⇒ **algebraic independence of logarithms of algebraic numbers**, in the only form
used below: `ℚ`-linearly independent complex numbers whose exponentials are all algebraic are
themselves algebraically independent. -/
theorem algebraicIndependent_of_exp_isAlgebraic (hS : SchanuelConjecture) {n : ℕ}
    (z : Fin n → ℂ) (hz : LinearIndependent ℚ z)
    (he : ∀ i, IsAlgebraic ℚ (Complex.exp (z i))) : AlgebraicIndependent ℚ z := by
  refine algebraicIndependent_of_schanuel hS z hz z ?_
  rintro w (⟨i, rfl⟩ | ⟨i, rfl⟩)
  · exact isAlgebraic_algebraMap (R := IntermediateField.adjoin ℚ (Set.range z)) (A := ℂ)
      ⟨_, subset_adjoin _ _ ⟨i, rfl⟩⟩
  · exact ((he i).tower_top _)

/-- **The rank obstruction.** An algebraically independent family of size `n` cannot live inside
a field generated by fewer than `n` elements (encoded: by a non-injective family `w` of size
`n`). -/
theorem false_of_algebraicIndependent_mem {n : ℕ} {y w : Fin n → ℂ}
    (hy : AlgebraicIndependent ℚ y) (hw : ¬ Function.Injective w)
    (hmem : ∀ i, y i ∈ IntermediateField.adjoin ℚ (Set.range w)) : False := by
  have h1 : (n : Cardinal) ≤ Algebra.trdeg ℚ (IntermediateField.adjoin ℚ (Set.range y)) :=
    hy.le_trdeg_adjoin
  have hstep : ∀ v ∈ Set.range w,
      IsAlgebraic (IntermediateField.adjoin ℚ (Set.range w)) v := by
    rintro v ⟨i, rfl⟩
    exact isAlgebraic_algebraMap (R := IntermediateField.adjoin ℚ (Set.range w)) (A := ℂ)
      ⟨_, subset_adjoin _ _ ⟨i, rfl⟩⟩
  have hgen : ∀ v ∈ Set.range y,
      IsAlgebraic (IntermediateField.adjoin ℚ (Set.range w)) v := by
    rintro v ⟨i, rfl⟩
    exact isAlgebraic_algebraMap (R := IntermediateField.adjoin ℚ (Set.range w)) (A := ℂ)
      ⟨_, hmem i⟩
  have h2 : Algebra.trdeg ℚ (IntermediateField.adjoin ℚ (Set.range y)) ≤
      Algebra.trdeg ℚ (IntermediateField.adjoin ℚ (Set.range w)) :=
    trdeg_le_adjoin_of_forall_isAlgebraic (forall_isAlgebraic_adjoin hgen)
  exact hw (algebraicIndependent_of_le_trdeg_adjoin w (h1.trans h2)).injective

theorem snoc3 (a b c : ℂ) : Fin.snoc ![a, b] c = ![a, b, c] := by
  funext i; fin_cases i <;> rfl

theorem snoc4 (a b c d : ℂ) : Fin.snoc ![a, b, c] d = ![a, b, c, d] := by
  funext i; fin_cases i <;> rfl

/-- Scaling a `ℚ`-linearly independent family by a nonzero complex number. -/
theorem linearIndependent_const_mul {n : ℕ} {v : Fin n → ℂ} (h : LinearIndependent ℚ v) {c : ℂ}
    (hc : c ≠ 0) : LinearIndependent ℚ (fun i => c * v i) := by
  rw [Fintype.linearIndependent_iff] at h ⊢
  intro g hg i
  refine h g ?_ i
  have hz : c * ∑ j, g j • v j = 0 := by
    rw [Finset.mul_sum, ← hg]
    exact Finset.sum_congr rfl fun j _ => by simp [Rat.smul_def]; ring
  exact (mul_eq_zero.1 hz).resolve_left hc

theorem ratCast_mem_adjoin (S : IntermediateField ℚ ℂ) (q : ℚ) : ((q : ℚ) : ℂ) ∈ S := by
  simpa using S.algebraMap_mem q

/-- **The heart of "Schanuel ⇒ four exponentials".**  Four numbers `a, b, c, d` with
`a·d = b·c`, with `a, b` and `a, c` each `ℚ`-linearly independent, cannot all have algebraic
exponentials. -/
theorem false_of_exp_algebraic_of_quad (hS : SchanuelConjecture) {a b c d : ℂ}
    (hab : LinearIndependent ℚ ![a, b]) (hac : LinearIndependent ℚ ![a, c])
    (hrel : a * d = b * c)
    (hea : IsAlgebraic ℚ (Complex.exp a)) (heb : IsAlgebraic ℚ (Complex.exp b))
    (hec : IsAlgebraic ℚ (Complex.exp c)) (hed : IsAlgebraic ℚ (Complex.exp d)) : False := by
  have ha0 : a ≠ 0 := by simpa using hab.ne_zero 0
  -- `a, b` are algebraically independent (Schanuel on the linearly independent pair)
  have hABind : AlgebraicIndependent ℚ ![a, b] :=
    algebraicIndependent_of_exp_isAlgebraic hS _ hab (by intro i; fin_cases i <;> assumption)
  by_cases h3 : LinearIndependent ℚ ![a, b, c]
  · have hABCind : AlgebraicIndependent ℚ ![a, b, c] :=
      algebraicIndependent_of_exp_isAlgebraic hS _ h3 (by intro i; fin_cases i <;> assumption)
    by_cases h4 : LinearIndependent ℚ ![a, b, c, d]
    · -- all four independent: but `d = bc/a` lies in `ℚ(a,b,c)`
      have hABCDind : AlgebraicIndependent ℚ ![a, b, c, d] :=
        algebraicIndependent_of_exp_isAlgebraic hS _ h4 (by intro i; fin_cases i <;> assumption)
      refine false_of_algebraicIndependent_mem hABCDind (w := ![a, b, c, c]) ?_ ?_
      · intro h
        have : (2 : Fin 4) = 3 := h rfl
        simp at this
      · set L := IntermediateField.adjoin ℚ (Set.range ![a, b, c, c]) with hL
        have hma : a ∈ L := subset_adjoin _ _ ⟨0, rfl⟩
        have hmb : b ∈ L := subset_adjoin _ _ ⟨1, rfl⟩
        have hmc : c ∈ L := subset_adjoin _ _ ⟨2, rfl⟩
        have hd : d = b * c / a := by
          rw [eq_div_iff ha0]; linear_combination hrel
        intro i; fin_cases i
        · exact hma
        · exact hmb
        · exact hmc
        · show d ∈ L
          rw [hd]
          exact div_mem (mul_mem hmb hmc) hma
    · -- `d` is a rational combination of `a, b, c`; solve the relation for `c`
      rw [← snoc4, linearIndependent_finSnoc] at h4
      have hdspan : d ∈ Submodule.span ℚ (Set.range ![a, b, c]) := by
        by_contra hn; exact h4 ⟨h3, hn⟩
      obtain ⟨g, hg⟩ := (Submodule.mem_span_range_iff_exists_fun ℚ).1 hdspan
      rw [Fin.sum_univ_three] at hg
      simp only [Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons,
        Matrix.cons_val_two, Matrix.tail_cons, Rat.smul_def] at hg
      -- `hg : ↑(g 0) * a + ↑(g 1) * b + ↑(g 2) * c = d`
      have hden : (g 2 : ℂ) * a - b ≠ 0 := by
        intro h
        have := (LinearIndependent.pair_iff.1 hab) (g 2) (-1) (by
          simp only [Rat.smul_def]; push_cast; linear_combination h)
        simpa using this.2
      have hc : c = -((g 0 : ℂ) * a * a + (g 1 : ℂ) * a * b) / ((g 2 : ℂ) * a - b) := by
        rw [eq_div_iff hden]
        linear_combination hrel + a * hg
      refine false_of_algebraicIndependent_mem hABCind (w := ![a, b, b]) ?_ ?_
      · intro h
        have : (1 : Fin 3) = 2 := h rfl
        simp at this
      · set L := IntermediateField.adjoin ℚ (Set.range ![a, b, b]) with hL
        have hma : a ∈ L := subset_adjoin _ _ ⟨0, rfl⟩
        have hmb : b ∈ L := subset_adjoin _ _ ⟨1, rfl⟩
        intro i; fin_cases i
        · exact hma
        · exact hmb
        · show c ∈ L
          rw [hc]
          exact div_mem
            (neg_mem (add_mem (mul_mem (mul_mem (ratCast_mem_adjoin L (g 0)) hma) hma)
              (mul_mem (mul_mem (ratCast_mem_adjoin L (g 1)) hma) hmb)))
            (sub_mem (mul_mem (ratCast_mem_adjoin L (g 2)) hma) hmb)
  · -- `c = p a + q b`
    rw [← snoc3, linearIndependent_finSnoc] at h3
    have hcspan : c ∈ Submodule.span ℚ (Set.range ![a, b]) := by
      by_contra hn; exact h3 ⟨hab, hn⟩
    obtain ⟨g, hg⟩ := (Submodule.mem_span_range_iff_exists_fun ℚ).1 hcspan
    rw [Fin.sum_univ_two] at hg
    simp only [Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons, Rat.smul_def] at hg
    have hq : (g 1 : ℚ) ≠ 0 := by
      intro h
      have := (LinearIndependent.pair_iff.1 hac) (g 0) (-1) (by
        simp only [Rat.smul_def]; push_cast; rw [h] at hg; push_cast at hg; linear_combination hg)
      simpa using this.2
    by_cases h3' : LinearIndependent ℚ ![a, b, d]
    · have hABDind : AlgebraicIndependent ℚ ![a, b, d] :=
        algebraicIndependent_of_exp_isAlgebraic hS _ h3' (by intro i; fin_cases i <;> assumption)
      refine false_of_algebraicIndependent_mem hABDind (w := ![a, b, b]) ?_ ?_
      · intro h
        have : (1 : Fin 3) = 2 := h rfl
        simp at this
      · set L := IntermediateField.adjoin ℚ (Set.range ![a, b, b]) with hL
        have hma : a ∈ L := subset_adjoin _ _ ⟨0, rfl⟩
        have hmb : b ∈ L := subset_adjoin _ _ ⟨1, rfl⟩
        have hd : d = ((g 0 : ℂ) * a * b + (g 1 : ℂ) * b * b) / a := by
          rw [eq_div_iff ha0]; linear_combination hrel - b * hg
        intro i; fin_cases i
        · exact hma
        · exact hmb
        · show d ∈ L
          rw [hd]
          exact div_mem (add_mem (mul_mem (mul_mem (ratCast_mem_adjoin L (g 0)) hma) hmb)
            (mul_mem (mul_mem (ratCast_mem_adjoin L (g 1)) hmb) hmb)) hma
    · -- `d = u a + v b` too: everything collapses into `ℚ(a,b)` and `b` becomes quadratic over `ℚ(a)`
      rw [← snoc3, linearIndependent_finSnoc] at h3'
      have hdspan : d ∈ Submodule.span ℚ (Set.range ![a, b]) := by
        by_contra hn; exact h3' ⟨hab, hn⟩
      obtain ⟨h, hh⟩ := (Submodule.mem_span_range_iff_exists_fun ℚ).1 hdspan
      rw [Fin.sum_univ_two] at hh
      simp only [Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons, Rat.smul_def] at hh
      set L := IntermediateField.adjoin ℚ ({a} : Set ℂ) with hL
      have hma : a ∈ L := subset_adjoin _ _ rfl
      have hqC : ((g 1 : ℚ) : ℂ) ≠ 0 := by exact_mod_cast hq
      have hquad : b * b = ((h 0 : ℂ) / (g 1 : ℂ)) * (a * a)
          + (((h 1 : ℂ) - (g 0 : ℂ)) / (g 1 : ℂ)) * (a * b) := by
        field_simp
        linear_combination b * hg - a * hh - hrel
      refine not_isAlgebraic_of_algebraicIndependent_pair hABind ?_
      set A : L := ⟨((h 1 : ℂ) - (g 0 : ℂ)) / (g 1 : ℂ) * a,
        mul_mem (div_mem (sub_mem (ratCast_mem_adjoin L (h 1)) (ratCast_mem_adjoin L (g 0)))
          (ratCast_mem_adjoin L (g 1))) hma⟩ with hA
      set B : L := ⟨(h 0 : ℂ) / (g 1 : ℂ) * (a * a),
        mul_mem (div_mem (ratCast_mem_adjoin L (h 0)) (ratCast_mem_adjoin L (g 1)))
          (mul_mem hma hma)⟩ with hB
      refine ⟨Polynomial.X ^ 2 - Polynomial.C A * Polynomial.X - Polynomial.C B, ?_, ?_⟩
      · have hm : (Polynomial.X ^ 2 - Polynomial.C A * Polynomial.X - Polynomial.C B :
            Polynomial L).Monic := by monicity!
        exact hm.ne_zero
      · simp only [map_sub, map_mul, map_pow, Polynomial.aeval_X, Polynomial.aeval_C]
        show b ^ 2 - (A : ℂ) * b - (B : ℂ) = 0
        simp only [hA, hB]
        linear_combination hquad

/-- Schanuel ⇒ the four exponentials conjecture. -/
theorem fourExponentials_of_schanuel (hS : SchanuelConjecture) : FourExponentialsConjecture := by
  intro x y hx hy
  by_contra hcon
  simp only [Transcendental, not_exists, not_not] at hcon
  have hab : LinearIndependent ℚ ![x 0 * y 0, x 0 * y 1] := by
    have h := linearIndependent_const_mul hy (c := x 0) (hx.ne_zero 0)
    have he : (fun i => x 0 * y i) = ![x 0 * y 0, x 0 * y 1] := by
      funext i; fin_cases i <;> rfl
    rwa [he] at h
  have hac : LinearIndependent ℚ ![x 0 * y 0, x 1 * y 0] := by
    have h := linearIndependent_const_mul hx (c := y 0) (hy.ne_zero 0)
    have he : (fun i => y 0 * x i) = ![x 0 * y 0, x 1 * y 0] := by
      funext i; fin_cases i <;> simp [mul_comm]
    rwa [he] at h
  exact false_of_exp_algebraic_of_quad hS hab hac (by ring)
    (hcon 0 0) (hcon 0 1) (hcon 1 0) (hcon 1 1)


/-- Four exponentials ⇒ for irrational `t`, `2^t` or `3^t` is transcendental. -/
theorem two_rpow_or_three_rpow_transcendental (h4 : FourExponentialsConjecture) {t : ℝ}
    (ht : Irrational t) :
    Transcendental ℚ ((2 : ℝ) ^ t) ∨ Transcendental ℚ ((3 : ℝ) ^ t) := by
  sorry

/-- **Unconditional**, from the six exponentials theorem: if `pᵢ^t` is an integer for three
distinct primes `pᵢ`, then `t` is a natural number. -/
theorem eq_nat_of_three_primes_rpow (h6 : SixExponentials) {t : ℝ} {p : Fin 3 → Nat.Primes}
    (hp : Function.Injective p) (h : ∀ i, ∃ n : ℕ, ((p i : ℕ) : ℝ) ^ t = n) :
    ∃ n : ℕ, t = n := by
  sorry

/-- Schanuel ⇒ `e, e^e, e^{e^e}` are algebraically independent: take `z = (1, e, e^e)`. -/
theorem algebraicIndependent_exp_tower_three (hS : SchanuelConjecture) :
    AlgebraicIndependent ℚ
      ![Real.exp 1, Real.exp (Real.exp 1), Real.exp (Real.exp (Real.exp 1))] := by
  sorry

/-- Schanuel ⇒ `π` together with the logarithms of distinct primes are algebraically
independent: take `z = (iπ, log p₁, …, log pₙ)`. -/
theorem algebraicIndependent_pi_log_primes (hS : SchanuelConjecture) {n : ℕ}
    (p : Fin n → Nat.Primes) (hp : Function.Injective p) :
    AlgebraicIndependent ℚ
      (Fin.cons Real.pi fun i ↦ Real.log (p i : ℕ) : Fin (n + 1) → ℝ) := by
  sorry

/-- Schanuel ⇒ `e + log 2` is transcendental: `e` and `log 2` are algebraically independent,
by taking `z = (1, log 2)`. -/
theorem transcendental_exp_one_add_log_two (hS : SchanuelConjecture) :
    Transcendental ℚ (Real.exp 1 + Real.log 2) := by
  sorry

end LeanFormalizations.Exponentials
