/-
Copyright (c) 2026 Trevor Morris. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Trevor Morris
-/

/-
# What follows from Schanuel's conjecture

Every theorem here takes `hS : SchanuelConjecture` (`Literature/Schanuel.lean`).  The point
(Trevor, 2026-09-29) is to write down what we believe and see what falls out: a contradiction
with another hypothesis in the repo, a Maze row's `reopenIf` turning out to be implied, or a
surprising corollary.

Three kinds of consequence:

* **Consistency edges**: things already proved unconditionally (Lindemann–Weierstrass,
  Gelfond–Schneider, Nesterenko's `π, e^π`).  Deriving them from Schanuel checks that the
  statement says what we think it says.
* **Open consequences**: `e` and `π` algebraically independent, so `e + π` and `eπ` are
  transcendental; `e, e^e` algebraically independent; logarithms of distinct primes
  algebraically independent (Baker only gives linear independence).
* **Wright towers** (`Maze.lean`, Wright row): for rational non-integer `ω`, every level
  `tower ω n` with `n ≥ 2` is transcendental.  Proof sketch, by induction on `n`: with
  `L = log 2` and `gₖ = tower ω k`, apply Schanuel to `(L, g₁L, …, g_{n-1}L)`.  Linear independence
  of `1, g₁, …, g_{n-1}` comes from the previous step, because `g₁` is algebraic and irrational
  while `L, g₂, …, g_{n-1}` are algebraically independent.  The exponentials are
  `2, g₂, …, gₙ`, so the transcendence degree of `ℚ(L, g₂, …, gₙ)` is at least `n`, which makes
  that set algebraically independent.  This does **not** reach irrationality of the least Wright
  constant: all these levels being transcendental is consistent with every `gₖ` sitting just
  above a prime.

Proof sketches for the other results are the standard ones (Lang, *Introduction to
Transcendental Numbers*; Waldschmidt's surveys): pick `z` so that the exponentials are
algebraic or already in the field, then count.  Split into named leaves freely.  Frozen: every
statement below, and all of `Literature/`.
-/
import LeanFormalizations.Literature.Schanuel
import LeanFormalizations.Literature.GelfondSchneider
import LeanFormalizations.Literature.Lindemann
import LeanFormalizations.NumberTheory.Mills.Wright
import LeanFormalizations.NumberTheory.Transcendence.ETranscendental

namespace LeanFormalizations.Schanuel

open LeanFormalizations.Literature LeanFormalizations.Mills


/-!
## Toolkit: turning a transcendence-degree bound into algebraic independence

Schanuel's conjecture delivers `n ≤ trdeg ℚ ℚ(z, e^z)`.  All the consequences below are of the
form "these `n` numbers are algebraically independent", so the recurring step is:

* `algebraicIndependent_of_le_trdeg_adjoin` — a family of `n` elements generating a field of
  transcendence degree `≥ n` is algebraically independent.  (`mathlib`'s
  `Algebra.IsAlgebraic.isTranscendenceBasis_of_le_trdeg_of_finite`, after checking that the
  field is algebraic over the *algebra* generated by the family — which is its fraction field.)
* `trdeg_le_adjoin_of_forall_isAlgebraic` — passing to an algebraic extension does not change
  the transcendence degree, so the Schanuel field may be replaced by any field it is algebraic
  over.  This is what lets `ℚ(iπ, e)` be traded for `ℚ(π, e)`.

These are stated for a general base field, deliberately: with `F = ℚ` the two `Algebra ℚ ↥K`
instances (`DivisionRing.toRatAlgebra` and `IntermediateField.algebra'`) are not syntactically
equal and instance search fails inside the proofs.
-/

section Toolkit

open IntermediateField Algebra Cardinal Set
open scoped IntermediateField.algebraAdjoinAdjoin

variable {F E : Type} [Field F] [Field E] [Algebra F E]

/-- A field generated (as a field) by `s` is algebraic over the *algebra* generated by `s`:
it is its fraction field. -/
theorem isAlgebraic_algebraAdjoin_of_adjoin_eq_top
    {s : Set E} (h : IntermediateField.adjoin F s = ⊤) :
    Algebra.IsAlgebraic (Algebra.adjoin F s) E := by
  have H : Algebra.IsAlgebraic (Algebra.adjoin F s) (IntermediateField.adjoin F s) :=
    inferInstance
  let f := IsScalarTower.toAlgHom (Algebra.adjoin F s) (IntermediateField.adjoin F s) E
  constructor
  intro a
  have ha : a ∈ IntermediateField.adjoin F s := h ▸ trivial
  have hf : f (⟨a, ha⟩ : (IntermediateField.adjoin F s)) = a := rfl
  exact hf ▸ (H.isAlgebraic (⟨a, ha⟩ : (IntermediateField.adjoin F s))).algHom f

/-- **The counting step.** `n` elements generating a field of transcendence degree at least `n`
are algebraically independent. -/
theorem algebraicIndependent_of_le_trdeg_adjoin
    {n : ℕ} (x : Fin n → E)
    (h : (n : Cardinal) ≤ Algebra.trdeg F (IntermediateField.adjoin F (Set.range x))) :
    AlgebraicIndependent F x := by
  set K := IntermediateField.adjoin F (Set.range x) with hK
  set x' : Fin n → K := fun i => ⟨x i, subset_adjoin _ _ (mem_range_self i)⟩ with hx'
  have hval : (fun i => (x' i : E)) = x := rfl
  have htop : IntermediateField.adjoin F (Set.range x') = ⊤ := by
    apply IntermediateField.map_injective K.val
    rw [adjoin_map, ← Set.range_comp]
    show IntermediateField.adjoin F (Set.range x) = _
    ext y
    simp only [IntermediateField.mem_map]
    constructor
    · intro hy; exact ⟨⟨y, hy⟩, trivial, rfl⟩
    · rintro ⟨⟨z, hz⟩, -, rfl⟩; exact hz
  haveI := isAlgebraic_algebraAdjoin_of_adjoin_eq_top htop
  have hb := Algebra.IsAlgebraic.isTranscendenceBasis_of_le_trdeg_of_finite F x'
    (by simpa using h)
  exact hval ▸ hb.1.map' (f := K.val) (Subtype.val_injective)

/-- The converse direction of the counting step. -/
theorem AlgebraicIndependent.le_trdeg_adjoin {n : ℕ} {x : Fin n → E}
    (hx : AlgebraicIndependent F x) :
    (n : Cardinal) ≤ Algebra.trdeg F (IntermediateField.adjoin F (Set.range x)) := by
  set K := IntermediateField.adjoin F (Set.range x) with hK
  set x' : Fin n → K := fun i => ⟨x i, subset_adjoin _ _ (mem_range_self i)⟩ with hx'
  have : AlgebraicIndependent F x' := AlgebraicIndependent.of_comp K.val hx
  simpa using this.cardinalMk_le_trdeg

set_option synthInstance.maxHeartbeats 400000 in
/-- Transcendence degree is unchanged by an algebraic extension (the `trdeg L N = 0` half of
the tower formula). -/
theorem trdeg_le_of_isAlgebraic' {L N : IntermediateField F E} (hLN : L ≤ N)
    (halg : Algebra.IsAlgebraic L (IntermediateField.extendScalars hLN)) :
    Algebra.trdeg F N ≤ Algebra.trdeg F L := by
  haveI := halg
  have h2 : Algebra.trdeg F L + Algebra.trdeg L (IntermediateField.extendScalars hLN) =
      Algebra.trdeg F (IntermediateField.extendScalars hLN) := trdeg_add_eq F L
  rw [trdeg_eq_zero (R := L) (A := IntermediateField.extendScalars hLN), add_zero] at h2
  exact h2.symm.le

set_option synthInstance.maxHeartbeats 400000 in
/-- If every element of `N` is algebraic over `L` (no containment assumed), then `N` has no
more transcendence degree than `L`. -/
theorem trdeg_le_adjoin_of_forall_isAlgebraic {L N : IntermediateField F E}
    (halg : ∀ w ∈ N, IsAlgebraic L w) : Algebra.trdeg F N ≤ Algebra.trdeg F L := by
  have hmono : Algebra.trdeg F N ≤ Algebra.trdeg F ↥(L ⊔ N) :=
    trdeg_le_of_injective (IntermediateField.inclusion (le_sup_right : N ≤ L ⊔ N))
      (IntermediateField.inclusion (le_sup_right : N ≤ L ⊔ N)).injective
  refine hmono.trans (trdeg_le_of_isAlgebraic' (L := L) (N := L ⊔ N) le_sup_left ?_)
  constructor
  intro a
  rw [IntermediateField.isAlgebraic_iff]
  have : (L ⊔ N : IntermediateField F E) ≤ (algebraicClosure L E).restrictScalars F := by
    refine sup_le ?_ ?_
    · intro w hw
      exact mem_algebraicClosure_iff.2 (isAlgebraic_algebraMap (R := L) (⟨w, hw⟩ : L))
    · intro w hw
      exact mem_algebraicClosure_iff.2 (halg w hw)
  exact mem_algebraicClosure_iff.1 (this a.2)

/-- Algebraicity over `L` propagates from a generating set to the field it generates. -/
theorem forall_isAlgebraic_adjoin {L : IntermediateField F E} {S : Set E}
    (h : ∀ w ∈ S, IsAlgebraic L w) : ∀ w ∈ IntermediateField.adjoin F S, IsAlgebraic L w := by
  have hle : IntermediateField.adjoin F S ≤ (algebraicClosure L E).restrictScalars F :=
    IntermediateField.adjoin_le_iff.2 fun w hw => mem_algebraicClosure_iff.2 (h w hw)
  exact fun w hw => mem_algebraicClosure_iff.1 (hle hw)

/-- **The master step.** `n` elements `y` are algebraically independent as soon as some field
`N` of transcendence degree `≥ n` is algebraic over `ℚ(y)`. -/
theorem algebraicIndependent_of_le_trdeg_of_isAlgebraic {n : ℕ} (y : Fin n → E)
    (N : IntermediateField F E) (h : (n : Cardinal) ≤ Algebra.trdeg F N)
    (halg : ∀ w ∈ N, IsAlgebraic (IntermediateField.adjoin F (Set.range y)) w) :
    AlgebraicIndependent F y :=
  algebraicIndependent_of_le_trdeg_adjoin y
    (h.trans (trdeg_le_adjoin_of_forall_isAlgebraic halg))

end Toolkit

/-! ## The Schanuel front-end and small helpers -/

open Complex IntermediateField Algebra Cardinal Set in
/-- **The form in which Schanuel's conjecture is used below.**  If `z` is `ℚ`-linearly
independent and every generator of `ℚ(z, e^z)` is algebraic over `ℚ(y)` for a family `y` of the
same size `n`, then `y` is algebraically independent. -/
theorem algebraicIndependent_of_schanuel (hS : SchanuelConjecture) {n : ℕ} (z : Fin n → ℂ)
    (hz : LinearIndependent ℚ z) (y : Fin n → ℂ)
    (halg : ∀ w ∈ Set.range z ∪ Set.range (Complex.exp ∘ z),
        IsAlgebraic (IntermediateField.adjoin ℚ (Set.range y)) w) :
    AlgebraicIndependent ℚ y := by
  have hsch := hS n z hz
  refine algebraicIndependent_of_le_trdeg_of_isAlgebraic y
    (IntermediateField.adjoin ℚ (Set.range z ∪ Set.range (Complex.exp ∘ z))) ?_
    (forall_isAlgebraic_adjoin halg)
  convert hsch using 2 <;> rfl

open Complex IntermediateField Algebra Set in
theorem isAlgebraic_I : IsAlgebraic ℚ Complex.I := by
  have hm : (Polynomial.X ^ 2 + 1 : Polynomial ℚ).Monic := by monicity!
  exact ⟨_, hm.ne_zero, by simp⟩

open IntermediateField Algebra in
theorem isAlgebraic_mul_rat {L : IntermediateField ℚ ℂ} {a b : ℂ}
    (ha : IsAlgebraic ℚ a) (hb : IsAlgebraic L b) : IsAlgebraic L (a * b) :=
  mem_algebraicClosure_iff.1
    (mul_mem (mem_algebraicClosure_iff.2 (ha.tower_top L)) (mem_algebraicClosure_iff.2 hb))

open IntermediateField Algebra in
theorem isAlgebraic_sub_rat {L : IntermediateField ℚ ℂ} {a b : ℂ}
    (ha : IsAlgebraic ℚ a) (hb : IsAlgebraic L b) : IsAlgebraic L (a - b) :=
  mem_algebraicClosure_iff.1
    (sub_mem (mem_algebraicClosure_iff.2 (ha.tower_top L)) (mem_algebraicClosure_iff.2 hb))

open IntermediateField Algebra in
theorem isAlgebraic_div_rat {L : IntermediateField ℚ ℂ} {a b : ℂ}
    (ha : IsAlgebraic ℚ a) (hb : IsAlgebraic L b) : IsAlgebraic L (a / b) :=
  mem_algebraicClosure_iff.1
    (div_mem (mem_algebraicClosure_iff.2 (ha.tower_top L)) (mem_algebraicClosure_iff.2 hb))

open Complex IntermediateField Algebra Cardinal Set in
/-- Two algebraically independent numbers: the second is transcendental over `ℚ` adjoin the
first.  (Used to turn algebraic independence of `e, π` into transcendence of `e + π`, `eπ`.) -/
theorem not_isAlgebraic_of_algebraicIndependent_pair {a b : ℂ}
    (h : AlgebraicIndependent ℚ ![a, b]) :
    ¬ IsAlgebraic (IntermediateField.adjoin ℚ ({a} : Set ℂ)) b := by
  intro hb
  have hrange : Set.range ![a, a] = ({a} : Set ℂ) := by ext w; simp
  have halg : ∀ w ∈ IntermediateField.adjoin ℚ (Set.range ![a, b]),
      IsAlgebraic (IntermediateField.adjoin ℚ (Set.range ![a, a])) w := by
    refine forall_isAlgebraic_adjoin ?_
    rintro w ⟨i, rfl⟩
    rw [hrange]
    fin_cases i
    · exact isAlgebraic_algebraMap (R := IntermediateField.adjoin ℚ ({a} : Set ℂ)) (A := ℂ)
        ⟨a, subset_adjoin _ _ rfl⟩
    · exact hb
  have h2 := (AlgebraicIndependent.le_trdeg_adjoin h).trans
    (trdeg_le_adjoin_of_forall_isAlgebraic halg)
  have hii := (algebraicIndependent_of_le_trdeg_adjoin ![a, a] h2).injective
  have : (0 : Fin 2) = 1 := hii (by simp)
  simp at this

/-- Transfer along `ℝ → ℂ`: a real family is algebraically independent iff its image is. -/
theorem algebraicIndependent_real_of_complex {n : ℕ} {y : Fin n → ℝ}
    (h : AlgebraicIndependent ℚ fun i => ((y i : ℝ) : ℂ)) : AlgebraicIndependent ℚ y :=
  AlgebraicIndependent.of_comp (IsScalarTower.toAlgHom ℚ ℝ ℂ) h

theorem isAlgebraic_complex_of_real {r : ℝ} (h : IsAlgebraic ℚ r) : IsAlgebraic ℚ ((r : ℝ) : ℂ) :=
  h.algHom (IsScalarTower.toAlgHom ℚ ℝ ℂ)

/-! ## Consistency edges (known unconditionally) -/

open Complex IntermediateField Algebra Cardinal Set in
/-- A field generated by a single element cannot have transcendence degree `≥ 2`. -/
theorem not_two_le_trdeg_adjoin_singleton {a : ℂ}
    (h : (2 : Cardinal) ≤ Algebra.trdeg ℚ (IntermediateField.adjoin ℚ ({a} : Set ℂ))) :
    False := by
  have hrange : Set.range ![a, a] = ({a} : Set ℂ) := by ext w; simp
  have h' : ((2 : ℕ) : Cardinal) ≤
      Algebra.trdeg ℚ (IntermediateField.adjoin ℚ (Set.range ![a, a])) := by
    rw [hrange]; exact_mod_cast h
  have hii := (algebraicIndependent_of_le_trdeg_adjoin ![a, a] h').injective
  have : (0 : Fin 2) = 1 := hii (by simp)
  simp at this

open Complex IntermediateField Algebra Cardinal Set in
/-- Schanuel ⇒ Gelfond–Schneider (real form): take `z = (log a, b log a)`.  These are
`ℚ`-linearly independent because `b` is irrational and `log a ≠ 0`, and their exponentials are
`a` and `a^b`.  If `a^b` were algebraic, all four generators would be algebraic over the
single-generator field `ℚ(log a)`, whose transcendence degree is at most `1 < 2`. -/
theorem gelfondSchneider_of_schanuel (hS : SchanuelConjecture) : GelfondSchneider1934 := by
  intro a b ha0 ha1 haalg hbalg hbirr hab
  -- `log a ≠ 0`
  have hlog : Real.log a ≠ 0 := Real.log_ne_zero_of_pos_of_ne_one ha0 ha1
  set ℓ : ℂ := ((Real.log a : ℝ) : ℂ) with hℓ
  have hℓ0 : ℓ ≠ 0 := by simpa [hℓ] using hlog
  -- the Schanuel input
  have hz : LinearIndependent ℚ ![ℓ, (b : ℂ) * ℓ] := by
    rw [LinearIndependent.pair_iff]
    intro s t hst
    simp only [Rat.smul_def] at hst
    have : ((s : ℂ) + (t : ℂ) * (b : ℂ)) * ℓ = 0 := by ring_nf; ring_nf at hst; linear_combination hst
    rcases mul_eq_zero.1 this with h | h
    · have hre : (s : ℝ) + (t : ℝ) * b = 0 := by
        have := congrArg Complex.re h; simpa using this
      by_cases ht : t = 0
      · subst ht; simp at hre ⊢; exact_mod_cast hre
      · exact absurd (hbirr.ne_rat (-s / t) (by push_cast; field_simp at hre ⊢; linarith))
          (by simp)
    · exact absurd h hℓ0
  have hsch := hS 2 ![ℓ, (b : ℂ) * ℓ] hz
  -- everything is algebraic over `ℚ(log a)`
  have hmem : ℓ ∈ IntermediateField.adjoin ℚ ({ℓ} : Set ℂ) := subset_adjoin _ _ rfl
  have hℓalg : IsAlgebraic (IntermediateField.adjoin ℚ ({ℓ} : Set ℂ)) ℓ :=
    isAlgebraic_algebraMap (R := IntermediateField.adjoin ℚ ({ℓ} : Set ℂ)) (A := ℂ) ⟨_, hmem⟩
  have hexp1 : Complex.exp ℓ = ((a : ℝ) : ℂ) := by
    rw [hℓ, ← Complex.ofReal_exp, Real.exp_log ha0]
  have hexp2 : Complex.exp ((b : ℂ) * ℓ) = (((a ^ b : ℝ)) : ℂ) := by
    rw [hℓ, ← Complex.ofReal_mul, ← Complex.ofReal_exp, Real.rpow_def_of_pos ha0]
    norm_num [mul_comm]
  have hgen : ∀ w ∈ Set.range ![ℓ, (b : ℂ) * ℓ] ∪
      Set.range (Complex.exp ∘ ![ℓ, (b : ℂ) * ℓ]),
      IsAlgebraic (IntermediateField.adjoin ℚ ({ℓ} : Set ℂ)) w := by
    rintro w (⟨i, rfl⟩ | ⟨i, rfl⟩)
    · fin_cases i
      · exact hℓalg
      · exact isAlgebraic_mul_rat (isAlgebraic_complex_of_real hbalg) hℓalg
    · fin_cases i
      · show IsAlgebraic _ (Complex.exp ℓ)
        rw [hexp1]
        exact (isAlgebraic_complex_of_real haalg).tower_top _
      · show IsAlgebraic _ (Complex.exp ((b : ℂ) * ℓ))
        rw [hexp2]
        exact (isAlgebraic_complex_of_real hab).tower_top _
  refine not_two_le_trdeg_adjoin_singleton (a := ℓ) ?_
  refine le_trans ?_ (trdeg_le_adjoin_of_forall_isAlgebraic (forall_isAlgebraic_adjoin hgen))
  convert hsch using 2 <;> rfl

/-- Schanuel ⇒ Lindemann–Weierstrass, algebraic-independence form: take `z = u`. -/
theorem lindemannWeierstrassAlgIndep_of_schanuel (hS : SchanuelConjecture) :
    LindemannWeierstrassAlgIndep := by
  sorry

open Complex IntermediateField Algebra Set in
/-- `iπ` and `π` are `ℚ`-linearly independent. -/
theorem linearIndependent_I_mul_pi_pi :
    LinearIndependent ℚ ![Complex.I * (Real.pi:ℂ), (Real.pi : ℂ)] := by
  rw [LinearIndependent.pair_iff]
  intro s t hst
  simp only [Rat.smul_def] at hst
  have him := congrArg Complex.im hst
  have hre := congrArg Complex.re hst
  simp [Real.pi_ne_zero] at him hre
  exact ⟨him, hre⟩

open Complex IntermediateField Algebra Set in
/-- `1` and an irrational real are `ℚ`-linearly independent in `ℂ`. -/
theorem linearIndependent_one_ofReal {x : ℝ} (hx : Irrational x) :
    LinearIndependent ℚ ![(1:ℂ), (x : ℂ)] := by
  rw [LinearIndependent.pair_iff]
  intro s t hst
  simp only [Rat.smul_def] at hst
  have hre := congrArg Complex.re hst
  simp at hre
  by_cases ht : t = 0
  · subst ht; simp at hre ⊢; exact hre
  · exfalso
    apply hx.ne_rat (-s/t)
    push_cast
    field_simp at hre ⊢
    linarith [hre]

open Complex IntermediateField Algebra Set in
/-- Schanuel ⇒ `π` and `e^π` are algebraically independent, complex form: take `z = (iπ, π)`,
whose exponentials are `−1` and `e^π`. -/
theorem algebraicIndependent_pi_exp_pi_complex (hS : SchanuelConjecture) :
    AlgebraicIndependent ℚ ![(Real.pi : ℂ), Complex.exp (Real.pi : ℂ)] := by
  refine algebraicIndependent_of_schanuel hS _ linearIndependent_I_mul_pi_pi
    ![(Real.pi : ℂ), Complex.exp (Real.pi : ℂ)] ?_
  have hmemP : ((Real.pi : ℝ) : ℂ) ∈
      IntermediateField.adjoin ℚ (Set.range ![(Real.pi : ℂ), Complex.exp (Real.pi : ℂ)]) :=
    subset_adjoin _ _ ⟨0, rfl⟩
  have hmemX : Complex.exp (Real.pi : ℂ) ∈
      IntermediateField.adjoin ℚ (Set.range ![(Real.pi : ℂ), Complex.exp (Real.pi : ℂ)]) :=
    subset_adjoin _ _ ⟨1, rfl⟩
  rintro w (⟨i, rfl⟩ | ⟨i, rfl⟩)
  · fin_cases i
    · exact isAlgebraic_mul_rat isAlgebraic_I (isAlgebraic_algebraMap
        (R := IntermediateField.adjoin ℚ
          (Set.range ![(Real.pi : ℂ), Complex.exp (Real.pi : ℂ)])) (A := ℂ) ⟨_, hmemP⟩)
    · exact isAlgebraic_algebraMap
        (R := IntermediateField.adjoin ℚ
          (Set.range ![(Real.pi : ℂ), Complex.exp (Real.pi : ℂ)])) (A := ℂ) ⟨_, hmemP⟩
  · fin_cases i
    · show IsAlgebraic _ (Complex.exp (Complex.I * (Real.pi : ℂ)))
      rw [show Complex.I * (Real.pi:ℂ) = (Real.pi:ℂ) * Complex.I by ring, Complex.exp_mul_I]
      simpa using (isAlgebraic_algebraMap
        (R := IntermediateField.adjoin ℚ
          (Set.range ![(Real.pi : ℂ), Complex.exp (Real.pi : ℂ)])) (A := ℂ) (-1))
    · exact isAlgebraic_algebraMap
        (R := IntermediateField.adjoin ℚ
          (Set.range ![(Real.pi : ℂ), Complex.exp (Real.pi : ℂ)])) (A := ℂ) ⟨_, hmemX⟩

/-- Schanuel ⇒ `π` and `e^π` are algebraically independent: take `z = (iπ, π)`.  Proved
unconditionally by Nesterenko (1996). -/
theorem algebraicIndependent_pi_exp_pi (hS : SchanuelConjecture) :
    AlgebraicIndependent ℚ ![Real.pi, Real.exp Real.pi] := by
  refine algebraicIndependent_real_of_complex ?_
  have h := algebraicIndependent_pi_exp_pi_complex hS
  have hcomp : (fun i => ((![Real.pi, Real.exp Real.pi] i : ℝ) : ℂ))
      = ![(Real.pi : ℂ), Complex.exp (Real.pi : ℂ)] := by
    funext i; fin_cases i <;> simp [Complex.ofReal_exp]
  rw [hcomp]; exact h

/-! ## Open consequences -/

open Complex IntermediateField Algebra Set in
/-- `1` and `iπ` are `ℚ`-linearly independent (one is real, the other purely imaginary). -/
theorem linearIndependent_one_I_mul_pi :
    LinearIndependent ℚ ![(1:ℂ), Complex.I * (Real.pi : ℂ)] := by
  rw [LinearIndependent.pair_iff]
  intro s t hst
  simp only [Rat.smul_def] at hst
  have him := congrArg Complex.im hst
  have hre := congrArg Complex.re hst
  simp at him hre
  exact ⟨hre, him⟩

open Complex IntermediateField Algebra Set in
/-- Schanuel ⇒ `e` and `π` are algebraically independent, complex form.  Apply Schanuel to
`z = (1, iπ)`: the exponentials are `e` and `−1`, so `ℚ(1, iπ, e, −1)` has transcendence degree
`≥ 2`, and that field is algebraic over `ℚ(e, π)` (only `i` is missing, and it is algebraic). -/
theorem algebraicIndependent_exp_one_pi_complex (hS : SchanuelConjecture) :
    AlgebraicIndependent ℚ ![Complex.exp 1, (Real.pi : ℂ)] := by
  refine algebraicIndependent_of_schanuel hS _ linearIndependent_one_I_mul_pi
    ![Complex.exp 1, (Real.pi : ℂ)] ?_
  have hmemE : Complex.exp 1 ∈
      IntermediateField.adjoin ℚ (Set.range ![Complex.exp 1, (Real.pi : ℂ)]) :=
    subset_adjoin _ _ ⟨0, rfl⟩
  have hmemP : ((Real.pi : ℝ) : ℂ) ∈
      IntermediateField.adjoin ℚ (Set.range ![Complex.exp 1, (Real.pi : ℂ)]) :=
    subset_adjoin _ _ ⟨1, rfl⟩
  rintro w (⟨i, rfl⟩ | ⟨i, rfl⟩)
  · fin_cases i
    · exact isAlgebraic_one
    · exact isAlgebraic_mul_rat isAlgebraic_I (isAlgebraic_algebraMap
        (R := IntermediateField.adjoin ℚ (Set.range ![Complex.exp 1, (Real.pi : ℂ)]))
        (A := ℂ) ⟨_, hmemP⟩)
  · fin_cases i
    · exact isAlgebraic_algebraMap
        (R := IntermediateField.adjoin ℚ (Set.range ![Complex.exp 1, (Real.pi : ℂ)]))
        (A := ℂ) ⟨_, hmemE⟩
    · show IsAlgebraic _ (Complex.exp (Complex.I * (Real.pi : ℂ)))
      rw [show Complex.I * (Real.pi:ℂ) = (Real.pi:ℂ) * Complex.I by ring, Complex.exp_mul_I]
      simpa using (isAlgebraic_algebraMap
        (R := IntermediateField.adjoin ℚ (Set.range ![Complex.exp 1, (Real.pi : ℂ)]))
        (A := ℂ) (-1))

/-- Schanuel ⇒ `e` and `π` are algebraically independent: take `z = (1, iπ)`. -/
theorem algebraicIndependent_exp_one_pi (hS : SchanuelConjecture) :
    AlgebraicIndependent ℚ ![Real.exp 1, Real.pi] := by
  refine algebraicIndependent_real_of_complex ?_
  have h := algebraicIndependent_exp_one_pi_complex hS
  have hcomp : (fun i => ((![Real.exp 1, Real.pi] i : ℝ) : ℂ))
      = ![Complex.exp 1, (Real.pi : ℂ)] := by
    funext i; fin_cases i <;> simp [Complex.ofReal_exp]
  rw [hcomp]; exact h

open Complex IntermediateField Algebra Set in
theorem isAlgebraic_adjoin_exp_one :
    IsAlgebraic (IntermediateField.adjoin ℚ ({Complex.exp 1} : Set ℂ)) (Complex.exp 1) :=
  isAlgebraic_algebraMap (R := IntermediateField.adjoin ℚ ({Complex.exp 1} : Set ℂ)) (A := ℂ)
    ⟨_, subset_adjoin _ _ rfl⟩

open Complex IntermediateField Algebra Set in
/-- Schanuel ⇒ `e + π` is transcendental: otherwise `π = (e + π) − e` would be algebraic over
`ℚ(e)`, contradicting the algebraic independence of `e` and `π`. -/
theorem transcendental_exp_one_add_pi (hS : SchanuelConjecture) :
    Transcendental ℚ (Real.exp 1 + Real.pi) := by
  intro h
  refine not_isAlgebraic_of_algebraicIndependent_pair
    (algebraicIndependent_exp_one_pi_complex hS) ?_
  have hC : IsAlgebraic ℚ (Complex.exp 1 + (Real.pi : ℂ)) := by
    simpa [Complex.ofReal_exp] using isAlgebraic_complex_of_real h
  have hrw : ((Real.pi : ℝ) : ℂ) = (Complex.exp 1 + (Real.pi : ℂ)) - Complex.exp 1 := by ring
  rw [hrw]
  exact isAlgebraic_sub_rat hC isAlgebraic_adjoin_exp_one

open Complex IntermediateField Algebra Set in
/-- Schanuel ⇒ `e · π` is transcendental: otherwise `π = (eπ)/e` would be algebraic over
`ℚ(e)`. -/
theorem transcendental_exp_one_mul_pi (hS : SchanuelConjecture) :
    Transcendental ℚ (Real.exp 1 * Real.pi) := by
  intro h
  refine not_isAlgebraic_of_algebraicIndependent_pair
    (algebraicIndependent_exp_one_pi_complex hS) ?_
  have hC : IsAlgebraic ℚ (Complex.exp 1 * (Real.pi : ℂ)) := by
    simpa [Complex.ofReal_exp] using isAlgebraic_complex_of_real h
  have hne : Complex.exp 1 ≠ 0 := Complex.exp_ne_zero 1
  have hrw : ((Real.pi : ℝ) : ℂ) = (Complex.exp 1 * (Real.pi : ℂ)) / Complex.exp 1 := by
    field_simp
  rw [hrw]
  exact isAlgebraic_div_rat hC isAlgebraic_adjoin_exp_one

open Complex IntermediateField Algebra Set in
/-- Schanuel ⇒ `e` and `e^e` are algebraically independent, complex form: take `z = (1, e)`,
which is `ℚ`-linearly independent because `e` is irrational (`e_transcendental`), with
exponentials `e` and `e^e`. -/
theorem algebraicIndependent_exp_one_exp_exp_one_complex (hS : SchanuelConjecture) :
    AlgebraicIndependent ℚ
      ![((Real.exp 1 : ℝ) : ℂ), Complex.exp ((Real.exp 1 : ℝ) : ℂ)] := by
  refine algebraicIndependent_of_schanuel hS _
    (linearIndependent_one_ofReal (LeanFormalizations.Transcendence.e_transcendental.irrational))
    ![((Real.exp 1 : ℝ) : ℂ), Complex.exp ((Real.exp 1 : ℝ) : ℂ)] ?_
  have hmemE : ((Real.exp 1 : ℝ) : ℂ) ∈ IntermediateField.adjoin ℚ
      (Set.range ![((Real.exp 1 : ℝ) : ℂ), Complex.exp ((Real.exp 1 : ℝ) : ℂ)]) :=
    subset_adjoin _ _ ⟨0, rfl⟩
  have hmemX : Complex.exp ((Real.exp 1 : ℝ) : ℂ) ∈ IntermediateField.adjoin ℚ
      (Set.range ![((Real.exp 1 : ℝ) : ℂ), Complex.exp ((Real.exp 1 : ℝ) : ℂ)]) :=
    subset_adjoin _ _ ⟨1, rfl⟩
  rintro w (⟨i, rfl⟩ | ⟨i, rfl⟩)
  · fin_cases i
    · exact isAlgebraic_one
    · exact isAlgebraic_algebraMap
        (R := IntermediateField.adjoin ℚ
          (Set.range ![((Real.exp 1 : ℝ) : ℂ), Complex.exp ((Real.exp 1 : ℝ) : ℂ)]))
        (A := ℂ) ⟨_, hmemE⟩
  · fin_cases i
    · show IsAlgebraic _ (Complex.exp 1)
      have heq : Complex.exp 1 = ((Real.exp 1 : ℝ) : ℂ) := by
        simp
      rw [heq]
      exact isAlgebraic_algebraMap
        (R := IntermediateField.adjoin ℚ
          (Set.range ![((Real.exp 1 : ℝ) : ℂ), Complex.exp ((Real.exp 1 : ℝ) : ℂ)]))
        (A := ℂ) ⟨_, hmemE⟩
    · show IsAlgebraic _ (Complex.exp ((Real.exp 1 : ℝ) : ℂ))
      exact isAlgebraic_algebraMap
        (R := IntermediateField.adjoin ℚ
          (Set.range ![((Real.exp 1 : ℝ) : ℂ), Complex.exp ((Real.exp 1 : ℝ) : ℂ)]))
        (A := ℂ) ⟨_, hmemX⟩

/-- Schanuel ⇒ `e` and `e^e` are algebraically independent: take `z = (1, e)`. -/
theorem algebraicIndependent_exp_one_exp_exp_one (hS : SchanuelConjecture) :
    AlgebraicIndependent ℚ ![Real.exp 1, Real.exp (Real.exp 1)] := by
  refine algebraicIndependent_real_of_complex ?_
  have h := algebraicIndependent_exp_one_exp_exp_one_complex hS
  have hcomp : (fun i => ((![Real.exp 1, Real.exp (Real.exp 1)] i : ℝ) : ℂ))
      = ![((Real.exp 1 : ℝ) : ℂ), Complex.exp ((Real.exp 1 : ℝ) : ℂ)] := by
    funext i; fin_cases i <;> simp [Complex.ofReal_exp]
  rw [hcomp]; exact h

/-- Schanuel ⇒ logarithms of distinct primes are algebraically independent: take
`z = (log p₁, …, log pₙ)`, which are `ℚ`-linearly independent by unique factorization, with
exponentials `pᵢ ∈ ℚ`. -/
theorem algebraicIndependent_log_primes (hS : SchanuelConjecture) {n : ℕ}
    (p : Fin n → Nat.Primes) (hp : Function.Injective p) :
    AlgebraicIndependent ℚ fun i ↦ Real.log (p i : ℕ) := by
  sorry

/-! ## Wright towers -/

/-- Schanuel ⇒ for rational non-integer `ω`, the numbers `log 2, tower ω 2, …, tower ω n` are
algebraically independent (the induction in the header). -/
theorem algebraicIndependent_wright_tower (hS : SchanuelConjecture) {q : ℚ} (hq : q.den ≠ 1)
    (n : ℕ) :
    AlgebraicIndependent ℚ
      (Fin.cons (Real.log 2) fun i : Fin n ↦ tower (q : ℝ) (i + 2) : Fin (n + 1) → ℝ) := by
  sorry

/-- Schanuel ⇒ every level `n ≥ 2` of the Wright tower at a rational non-integer point is
transcendental.  (Level 2 needs only Gelfond–Schneider: `Maze.WrightLevelTwoTranscendental`.) -/
theorem transcendental_wright_tower (hS : SchanuelConjecture) {q : ℚ} (hq : q.den ≠ 1)
    {n : ℕ} (hn : 2 ≤ n) : Transcendental ℚ (tower (q : ℝ) n) := by
  sorry

end LeanFormalizations.Schanuel
