/-
Copyright (c) 2026 Trevor Morris. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Trevor Morris
-/

/-
# What follows from Schanuel's conjecture

Every theorem here takes `hS : SchanuelConjecture` (`Literature/Schanuel.lean`).  The point
(Trevor, 2026-09-29) is to write down what we believe and see what falls out: a contradiction
with another hypothesis in the repo, a Maze row's `reopenIf` turning out to be implied, or a
surprising corollary.

Three kinds of consequence:

* **Consistency edges**: things already proved unconditionally (Lindemann–Weierstrass,
  Gelfond–Schneider, Nesterenko's `π, e^π`).  Deriving them from Schanuel checks that the
  statement says what we think it says.
* **Open consequences**: `e` and `π` algebraically independent, so `e + π` and `eπ` are
  transcendental; `e, e^e` algebraically independent; logarithms of distinct primes
  algebraically independent (Baker only gives linear independence).
* **Wright towers** (`Maze.lean`, Wright row): for rational non-integer `ω`, every level
  `tower ω n` with `n ≥ 2` is transcendental.  Proof sketch, by induction on `n`: with
  `L = log 2` and `gₖ = tower ω k`, apply Schanuel to `(L, g₁L, …, g_{n-1}L)`.  Linear independence
  of `1, g₁, …, g_{n-1}` comes from the previous step, because `g₁` is algebraic and irrational
  while `L, g₂, …, g_{n-1}` are algebraically independent.  The exponentials are
  `2, g₂, …, gₙ`, so the transcendence degree of `ℚ(L, g₂, …, gₙ)` is at least `n`, which makes
  that set algebraically independent.  This does **not** reach irrationality of the least Wright
  constant: all these levels being transcendental is consistent with every `gₖ` sitting just
  above a prime.

Proof sketches for the other results are the standard ones (Lang, *Introduction to
Transcendental Numbers*; Waldschmidt's surveys): pick `z` so that the exponentials are
algebraic or already in the field, then count.  Split into named leaves freely.  Frozen: every
statement below, and all of `Literature/`.
-/
import LeanFormalizations.Literature.Schanuel
import LeanFormalizations.Literature.GelfondSchneider
import LeanFormalizations.Literature.Lindemann
import LeanFormalizations.NumberTheory.Mills.Wright

namespace LeanFormalizations.Schanuel

open LeanFormalizations.Literature LeanFormalizations.Mills


/-!
## Toolkit: turning a transcendence-degree bound into algebraic independence

Schanuel's conjecture delivers `n ≤ trdeg ℚ ℚ(z, e^z)`.  All the consequences below are of the
form "these `n` numbers are algebraically independent", so the recurring step is:

* `algebraicIndependent_of_le_trdeg_adjoin` — a family of `n` elements generating a field of
  transcendence degree `≥ n` is algebraically independent.  (`mathlib`'s
  `Algebra.IsAlgebraic.isTranscendenceBasis_of_le_trdeg_of_finite`, after checking that the
  field is algebraic over the *algebra* generated by the family — which is its fraction field.)
* `trdeg_le_adjoin_of_forall_isAlgebraic` — passing to an algebraic extension does not change
  the transcendence degree, so the Schanuel field may be replaced by any field it is algebraic
  over.  This is what lets `ℚ(iπ, e)` be traded for `ℚ(π, e)`.

These are stated for a general base field, deliberately: with `F = ℚ` the two `Algebra ℚ ↥K`
instances (`DivisionRing.toRatAlgebra` and `IntermediateField.algebra'`) are not syntactically
equal and instance search fails inside the proofs.
-/

section Toolkit

open IntermediateField Algebra Cardinal Set
open scoped IntermediateField.algebraAdjoinAdjoin

variable {F E : Type} [Field F] [Field E] [Algebra F E]

/-- A field generated (as a field) by `s` is algebraic over the *algebra* generated by `s`:
it is its fraction field. -/
theorem isAlgebraic_algebraAdjoin_of_adjoin_eq_top
    {s : Set E} (h : IntermediateField.adjoin F s = ⊤) :
    Algebra.IsAlgebraic (Algebra.adjoin F s) E := by
  have H : Algebra.IsAlgebraic (Algebra.adjoin F s) (IntermediateField.adjoin F s) :=
    inferInstance
  let f := IsScalarTower.toAlgHom (Algebra.adjoin F s) (IntermediateField.adjoin F s) E
  constructor
  intro a
  have ha : a ∈ IntermediateField.adjoin F s := h ▸ trivial
  have hf : f (⟨a, ha⟩ : (IntermediateField.adjoin F s)) = a := rfl
  exact hf ▸ (H.isAlgebraic (⟨a, ha⟩ : (IntermediateField.adjoin F s))).algHom f

/-- **The counting step.** `n` elements generating a field of transcendence degree at least `n`
are algebraically independent. -/
theorem algebraicIndependent_of_le_trdeg_adjoin
    {n : ℕ} (x : Fin n → E)
    (h : (n : Cardinal) ≤ Algebra.trdeg F (IntermediateField.adjoin F (Set.range x))) :
    AlgebraicIndependent F x := by
  set K := IntermediateField.adjoin F (Set.range x) with hK
  set x' : Fin n → K := fun i => ⟨x i, subset_adjoin _ _ (mem_range_self i)⟩ with hx'
  have hval : (fun i => (x' i : E)) = x := rfl
  have htop : IntermediateField.adjoin F (Set.range x') = ⊤ := by
    apply IntermediateField.map_injective K.val
    rw [adjoin_map, ← Set.range_comp]
    show IntermediateField.adjoin F (Set.range x) = _
    ext y
    simp only [IntermediateField.mem_map]
    constructor
    · intro hy; exact ⟨⟨y, hy⟩, trivial, rfl⟩
    · rintro ⟨⟨z, hz⟩, -, rfl⟩; exact hz
  haveI := isAlgebraic_algebraAdjoin_of_adjoin_eq_top htop
  have hb := Algebra.IsAlgebraic.isTranscendenceBasis_of_le_trdeg_of_finite F x'
    (by simpa using h)
  exact hval ▸ hb.1.map' (f := K.val) (Subtype.val_injective)

/-- The converse direction of the counting step. -/
theorem AlgebraicIndependent.le_trdeg_adjoin {n : ℕ} {x : Fin n → E}
    (hx : AlgebraicIndependent F x) :
    (n : Cardinal) ≤ Algebra.trdeg F (IntermediateField.adjoin F (Set.range x)) := by
  set K := IntermediateField.adjoin F (Set.range x) with hK
  set x' : Fin n → K := fun i => ⟨x i, subset_adjoin _ _ (mem_range_self i)⟩ with hx'
  have : AlgebraicIndependent F x' := AlgebraicIndependent.of_comp K.val hx
  simpa using this.cardinalMk_le_trdeg

set_option synthInstance.maxHeartbeats 400000 in
/-- Transcendence degree is unchanged by an algebraic extension (the `trdeg L N = 0` half of
the tower formula). -/
theorem trdeg_le_of_isAlgebraic' {L N : IntermediateField F E} (hLN : L ≤ N)
    (halg : Algebra.IsAlgebraic L (IntermediateField.extendScalars hLN)) :
    Algebra.trdeg F N ≤ Algebra.trdeg F L := by
  haveI := halg
  have h2 : Algebra.trdeg F L + Algebra.trdeg L (IntermediateField.extendScalars hLN) =
      Algebra.trdeg F (IntermediateField.extendScalars hLN) := trdeg_add_eq F L
  rw [trdeg_eq_zero (R := L) (A := IntermediateField.extendScalars hLN), add_zero] at h2
  exact h2.symm.le

set_option synthInstance.maxHeartbeats 400000 in
/-- If every element of `N` is algebraic over `L` (no containment assumed), then `N` has no
more transcendence degree than `L`. -/
theorem trdeg_le_adjoin_of_forall_isAlgebraic {L N : IntermediateField F E}
    (halg : ∀ w ∈ N, IsAlgebraic L w) : Algebra.trdeg F N ≤ Algebra.trdeg F L := by
  have hmono : Algebra.trdeg F N ≤ Algebra.trdeg F ↥(L ⊔ N) :=
    trdeg_le_of_injective (IntermediateField.inclusion (le_sup_right : N ≤ L ⊔ N))
      (IntermediateField.inclusion (le_sup_right : N ≤ L ⊔ N)).injective
  refine hmono.trans (trdeg_le_of_isAlgebraic' (L := L) (N := L ⊔ N) le_sup_left ?_)
  constructor
  intro a
  rw [IntermediateField.isAlgebraic_iff]
  have : (L ⊔ N : IntermediateField F E) ≤ (algebraicClosure L E).restrictScalars F := by
    refine sup_le ?_ ?_
    · intro w hw
      exact mem_algebraicClosure_iff.2 (isAlgebraic_algebraMap (R := L) (⟨w, hw⟩ : L))
    · intro w hw
      exact mem_algebraicClosure_iff.2 (halg w hw)
  exact mem_algebraicClosure_iff.1 (this a.2)

/-- Algebraicity over `L` propagates from a generating set to the field it generates. -/
theorem forall_isAlgebraic_adjoin {L : IntermediateField F E} {S : Set E}
    (h : ∀ w ∈ S, IsAlgebraic L w) : ∀ w ∈ IntermediateField.adjoin F S, IsAlgebraic L w := by
  have hle : IntermediateField.adjoin F S ≤ (algebraicClosure L E).restrictScalars F :=
    IntermediateField.adjoin_le_iff.2 fun w hw => mem_algebraicClosure_iff.2 (h w hw)
  exact fun w hw => mem_algebraicClosure_iff.1 (hle hw)

/-- **The master step.** `n` elements `y` are algebraically independent as soon as some field
`N` of transcendence degree `≥ n` is algebraic over `ℚ(y)`. -/
theorem algebraicIndependent_of_le_trdeg_of_isAlgebraic {n : ℕ} (y : Fin n → E)
    (N : IntermediateField F E) (h : (n : Cardinal) ≤ Algebra.trdeg F N)
    (halg : ∀ w ∈ N, IsAlgebraic (IntermediateField.adjoin F (Set.range y)) w) :
    AlgebraicIndependent F y :=
  algebraicIndependent_of_le_trdeg_adjoin y
    (h.trans (trdeg_le_adjoin_of_forall_isAlgebraic halg))

end Toolkit

/-! ## Consistency edges (known unconditionally) -/

/-- Schanuel ⇒ Gelfond–Schneider (real form): take `z = (log a, b log a)`. -/
theorem gelfondSchneider_of_schanuel (hS : SchanuelConjecture) : GelfondSchneider1934 := by
  sorry

/-- Schanuel ⇒ Lindemann–Weierstrass, algebraic-independence form: take `z = u`. -/
theorem lindemannWeierstrassAlgIndep_of_schanuel (hS : SchanuelConjecture) :
    LindemannWeierstrassAlgIndep := by
  sorry

/-- Schanuel ⇒ `π` and `e^π` are algebraically independent: take `z = (iπ, π)`.  Proved
unconditionally by Nesterenko (1996). -/
theorem algebraicIndependent_pi_exp_pi (hS : SchanuelConjecture) :
    AlgebraicIndependent ℚ ![Real.pi, Real.exp Real.pi] := by
  sorry

/-! ## Open consequences -/

/-- Schanuel ⇒ `e` and `π` are algebraically independent: take `z = (1, iπ)`. -/
theorem algebraicIndependent_exp_one_pi (hS : SchanuelConjecture) :
    AlgebraicIndependent ℚ ![Real.exp 1, Real.pi] := by
  sorry

/-- Schanuel ⇒ `e + π` is transcendental. -/
theorem transcendental_exp_one_add_pi (hS : SchanuelConjecture) :
    Transcendental ℚ (Real.exp 1 + Real.pi) := by
  sorry

/-- Schanuel ⇒ `e · π` is transcendental. -/
theorem transcendental_exp_one_mul_pi (hS : SchanuelConjecture) :
    Transcendental ℚ (Real.exp 1 * Real.pi) := by
  sorry

/-- Schanuel ⇒ `e` and `e^e` are algebraically independent: take `z = (1, e)`. -/
theorem algebraicIndependent_exp_one_exp_exp_one (hS : SchanuelConjecture) :
    AlgebraicIndependent ℚ ![Real.exp 1, Real.exp (Real.exp 1)] := by
  sorry

/-- Schanuel ⇒ logarithms of distinct primes are algebraically independent: take
`z = (log p₁, …, log pₙ)`, which are `ℚ`-linearly independent by unique factorization, with
exponentials `pᵢ ∈ ℚ`. -/
theorem algebraicIndependent_log_primes (hS : SchanuelConjecture) {n : ℕ}
    (p : Fin n → Nat.Primes) (hp : Function.Injective p) :
    AlgebraicIndependent ℚ fun i ↦ Real.log (p i : ℕ) := by
  sorry

/-! ## Wright towers -/

/-- Schanuel ⇒ for rational non-integer `ω`, the numbers `log 2, tower ω 2, …, tower ω n` are
algebraically independent (the induction in the header). -/
theorem algebraicIndependent_wright_tower (hS : SchanuelConjecture) {q : ℚ} (hq : q.den ≠ 1)
    (n : ℕ) :
    AlgebraicIndependent ℚ
      (Fin.cons (Real.log 2) fun i : Fin n ↦ tower (q : ℝ) (i + 2) : Fin (n + 1) → ℝ) := by
  sorry

/-- Schanuel ⇒ every level `n ≥ 2` of the Wright tower at a rational non-integer point is
transcendental.  (Level 2 needs only Gelfond–Schneider: `Maze.WrightLevelTwoTranscendental`.) -/
theorem transcendental_wright_tower (hS : SchanuelConjecture) {q : ℚ} (hq : q.den ≠ 1)
    {n : ℕ} (hn : 2 ≤ n) : Transcendental ℚ (tower (q : ℝ) n) := by
  sorry

end LeanFormalizations.Schanuel
